/**
 * SEO alias slugs for all 33 image conversion tools.
 *
 * 5 aliases per tool = 165 total alias URLs. Same pattern as
 * reel-downloader-aliases.ts and auto-caption-aliases.ts — each alias renders
 * the same underlying converter but with a unique H1, eyebrow, subline, and
 * metadata for a distinct search-intent keyword cluster. Each self-canonicalizes
 * so Google indexes it independently.
 */

export interface ConverterAlias {
  /** URL slug — the full path is /tools/<slug> */
  slug: string;
  /** Primary tool slug this alias belongs to (for tool resolution). */
  canonical: string;
  /** SEO title — ≤50 chars (template appends " | Trndinn"). */
  seoTitle: string;
  /** SEO meta description — 140-160 chars. */
  seoDescription: string;
  /** Keywords for meta + internal reporting. */
  keywords: string[];
  /** H1 text before the gradient-highlighted word. */
  h1Prefix: string;
  /** The gradient-highlighted word/phrase in the H1. */
  h1Highlight: string;
  /** H1 text after the gradient word. */
  h1Suffix: string;
  /** Small primary-tinted eyebrow badge above the hero. */
  eyebrow: string;
  /** Hero paragraph shown under the H1. */
  heroSubline: string;
}

const ALIASES: ConverterAlias[] = [
  // ═══════════════════════ png-to-jpg ═══════════════════════
  { slug: "png-to-jpeg", canonical: "png-to-jpg", seoTitle: "Free PNG to JPEG Converter — No Signup", seoDescription: "Convert PNG images to JPEG format online free. No signup, instant download. Images never leave your browser.", keywords: ["png to jpeg", "convert png to jpeg", "png jpeg converter online"], h1Prefix: "Convert", h1Highlight: "PNG to JPEG", h1Suffix: "for free.", eyebrow: "Free PNG to JPEG Converter — no signup, no watermark", heroSubline: "Upload any PNG and get a JPEG in seconds. No signup, no watermark, runs entirely in your browser." },
  { slug: "convert-png-to-jpg", canonical: "png-to-jpg", seoTitle: "Convert PNG to JPG Online Free — Instant", seoDescription: "Convert PNG images to JPG online free. Instant, no signup, no watermark. Browser-based — images never leave your device.", keywords: ["convert png to jpg", "convert png to jpg online"], h1Prefix: "Convert", h1Highlight: "PNG to JPG", h1Suffix: "online, free.", eyebrow: "PNG to JPG Converter — instant, browser-based", heroSubline: "Upload a PNG, get a JPG. No account, no watermark, no software install needed." },
  { slug: "free-png-to-jpg-converter", canonical: "png-to-jpg", seoTitle: "Free PNG to JPG Converter — No Watermark", seoDescription: "Free online PNG to JPG converter. No watermark, no signup, no file size limit. Download your JPG instantly.", keywords: ["free png to jpg converter", "png to jpg free"], h1Prefix: "Free", h1Highlight: "PNG to JPG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to JPG converter online. No watermark ever, no account required, no file size limits." },
  { slug: "png-jpg-converter-online", canonical: "png-to-jpg", seoTitle: "PNG to JPG Converter Online — Fast & Free", seoDescription: "Online PNG to JPG converter. Fast, free, no signup. Convert any PNG to JPG in seconds — all in your browser.", keywords: ["png jpg converter online", "png to jpg converter online"], h1Prefix: "The fast", h1Highlight: "PNG to JPG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to JPG", heroSubline: "Convert any PNG to JPG in seconds, right in your browser. No upload to a server, no waiting." },
  { slug: "change-png-to-jpg", canonical: "png-to-jpg", seoTitle: "Change PNG to JPG Online Free — No App", seoDescription: "Change PNG images to JPG format online. No app, no signup, instant conversion. Browser-based — works on any device.", keywords: ["change png to jpg", "how to change png to jpg"], h1Prefix: "Change", h1Highlight: "PNG to JPG", h1Suffix: "on any device.", eyebrow: "Change PNG to JPG — no app install needed", heroSubline: "Change any PNG to JPG online, free. Works on iPhone, Android, Mac, and Windows. No app required." },

  // ═══════════════════════ jpg-to-png ═══════════════════════
  { slug: "jpeg-to-png", canonical: "jpg-to-png", seoTitle: "Free JPEG to PNG Converter — No Signup", seoDescription: "Convert JPEG images to PNG format online free. Lossless output, no signup, instant download. Browser-based.", keywords: ["jpeg to png", "convert jpeg to png", "jpeg png converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to PNG", h1Suffix: "for free.", eyebrow: "Free JPEG to PNG Converter — lossless, no signup", heroSubline: "Upload any JPEG and get a lossless PNG in seconds. No signup, no watermark, all in your browser." },
  { slug: "convert-jpg-to-png", canonical: "jpg-to-png", seoTitle: "Convert JPG to PNG Online Free — Instant", seoDescription: "Convert JPG images to PNG online free. Instant, no signup, no watermark. Lossless output, browser-based.", keywords: ["convert jpg to png", "convert jpg to png online"], h1Prefix: "Convert", h1Highlight: "JPG to PNG", h1Suffix: "online, free.", eyebrow: "JPG to PNG Converter — instant, browser-based", heroSubline: "Upload a JPG, get a lossless PNG. No account, no watermark, no software install needed." },
  { slug: "free-jpg-to-png-converter", canonical: "jpg-to-png", seoTitle: "Free JPG to PNG Converter — No Watermark", seoDescription: "Free online JPG to PNG converter. No watermark, no signup, no file size limit. Download your PNG instantly.", keywords: ["free jpg to png converter", "jpg to png free"], h1Prefix: "Free", h1Highlight: "JPG to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free JPG to PNG converter online. No watermark ever, no account required, no size limits." },
  { slug: "jpg-png-converter-online", canonical: "jpg-to-png", seoTitle: "JPG to PNG Converter Online — Fast & Free", seoDescription: "Online JPG to PNG converter. Fast, free, no signup. Convert any JPG to lossless PNG in seconds.", keywords: ["jpg png converter online", "jpg to png converter online"], h1Prefix: "The fast", h1Highlight: "JPG to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to PNG", heroSubline: "Convert any JPG to lossless PNG in seconds, right in your browser. No server upload, no waiting." },
  { slug: "change-jpg-to-png", canonical: "jpg-to-png", seoTitle: "Change JPG to PNG Online Free — No App", seoDescription: "Change JPG images to PNG format online. No app, no signup, instant conversion. Works on any device.", keywords: ["change jpg to png", "how to change jpg to png"], h1Prefix: "Change", h1Highlight: "JPG to PNG", h1Suffix: "on any device.", eyebrow: "Change JPG to PNG — no app install needed", heroSubline: "Change any JPG to PNG online, free. Works on iPhone, Android, Mac, and Windows. No app required." },

  // ═══════════════════════ webp-to-jpg ═══════════════════════
  { slug: "convert-webp-to-jpg", canonical: "webp-to-jpg", seoTitle: "Convert WebP to JPG Online Free — Instant", seoDescription: "Convert WebP to JPG online free. Instant download, no signup. Make WebP files compatible with any app.", keywords: ["convert webp to jpg", "convert webp to jpg online"], h1Prefix: "Convert", h1Highlight: "WebP to JPG", h1Suffix: "online, free.", eyebrow: "WebP to JPG Converter — instant, browser-based", heroSubline: "Upload a WebP, get a universally compatible JPG. No account, no watermark, no install needed." },
  { slug: "webp-to-jpeg", canonical: "webp-to-jpg", seoTitle: "Free WebP to JPEG Converter — No Signup", seoDescription: "Convert WebP images to JPEG format online free. No signup, instant download. Images never leave your browser.", keywords: ["webp to jpeg", "convert webp to jpeg", "webp jpeg converter online"], h1Prefix: "Convert", h1Highlight: "WebP to JPEG", h1Suffix: "for free.", eyebrow: "Free WebP to JPEG Converter — no signup, no watermark", heroSubline: "Upload any WebP and get a JPEG in seconds. No signup, no watermark, runs entirely in your browser." },
  { slug: "free-webp-to-jpg-converter", canonical: "webp-to-jpg", seoTitle: "Free WebP to JPG Converter — No Watermark", seoDescription: "Free online WebP to JPG converter. No watermark, no signup, no file size limit. Download instantly.", keywords: ["free webp to jpg converter", "webp to jpg free"], h1Prefix: "Free", h1Highlight: "WebP to JPG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to JPG converter online. No watermark ever, no account required." },
  { slug: "webp-jpg-converter-online", canonical: "webp-to-jpg", seoTitle: "WebP to JPG Converter Online — Fast & Free", seoDescription: "Online WebP to JPG converter. Fast, free, no signup. Convert any WebP to JPG in seconds.", keywords: ["webp jpg converter online", "webp to jpg converter online"], h1Prefix: "The fast", h1Highlight: "WebP to JPG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to JPG", heroSubline: "Convert any WebP to JPG in seconds, right in your browser. No server upload, no waiting." },
  { slug: "change-webp-to-jpg", canonical: "webp-to-jpg", seoTitle: "Change WebP to JPG Online Free — No App", seoDescription: "Change WebP images to JPG format online. No app, no signup, instant conversion. Works on any device.", keywords: ["change webp to jpg", "how to change webp to jpg"], h1Prefix: "Change", h1Highlight: "WebP to JPG", h1Suffix: "on any device.", eyebrow: "Change WebP to JPG — no app install needed", heroSubline: "Change any WebP to JPG online, free. Works on iPhone, Android, Mac, and Windows." },

  // ═══════════════════════ webp-to-png ═══════════════════════
  { slug: "convert-webp-to-png", canonical: "webp-to-png", seoTitle: "Convert WebP to PNG Online Free — Instant", seoDescription: "Convert WebP to PNG online free. Instant download, no signup. Lossless PNG with transparency support.", keywords: ["convert webp to png", "convert webp to png online"], h1Prefix: "Convert", h1Highlight: "WebP to PNG", h1Suffix: "online, free.", eyebrow: "WebP to PNG Converter — instant, browser-based", heroSubline: "Upload a WebP, get a lossless PNG. No account, no watermark, no install needed." },
  { slug: "free-webp-to-png-converter", canonical: "webp-to-png", seoTitle: "Free WebP to PNG Converter — No Watermark", seoDescription: "Free online WebP to PNG converter. No watermark, no signup, no file size limit. Download instantly.", keywords: ["free webp to png converter", "webp to png free"], h1Prefix: "Free", h1Highlight: "WebP to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to PNG converter online. No watermark ever, no account required." },
  { slug: "webp-png-converter-online", canonical: "webp-to-png", seoTitle: "WebP to PNG Converter Online — Fast & Free", seoDescription: "Online WebP to PNG converter. Fast, free, no signup. Convert any WebP to lossless PNG in seconds.", keywords: ["webp png converter online", "webp to png converter online"], h1Prefix: "The fast", h1Highlight: "WebP to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to PNG", heroSubline: "Convert any WebP to lossless PNG in seconds, right in your browser." },
  { slug: "change-webp-to-png", canonical: "webp-to-png", seoTitle: "Change WebP to PNG Online Free — No App", seoDescription: "Change WebP images to PNG format online. No app, no signup, instant conversion. Works on any device.", keywords: ["change webp to png", "how to convert webp to png"], h1Prefix: "Change", h1Highlight: "WebP to PNG", h1Suffix: "on any device.", eyebrow: "Change WebP to PNG — no app install needed", heroSubline: "Change any WebP to PNG online, free. Works on iPhone, Android, Mac, and Windows." },
  { slug: "webp-to-png-transparent", canonical: "webp-to-png", seoTitle: "WebP to PNG — Transparency Preserved", seoDescription: "Convert WebP to PNG online free with transparency preserved. No signup, instant download, browser-based.", keywords: ["webp to png transparent", "webp to png with transparency"], h1Prefix: "Convert WebP to PNG with", h1Highlight: "transparency preserved", h1Suffix: ".", eyebrow: "WebP to PNG — alpha channel preserved", heroSubline: "Keep every transparent pixel intact when converting WebP to PNG. No signup, no watermark." },

  // ═══════════════════════ jpg-to-webp ═══════════════════════
  { slug: "convert-jpg-to-webp", canonical: "jpg-to-webp", seoTitle: "Convert JPG to WebP Online Free — Smaller", seoDescription: "Convert JPG to WebP online free. Get 25-35% smaller files for faster web loading. No signup, instant.", keywords: ["convert jpg to webp", "convert jpg to webp online"], h1Prefix: "Convert", h1Highlight: "JPG to WebP", h1Suffix: "online, free.", eyebrow: "JPG to WebP Converter — smaller, faster files", heroSubline: "Upload a JPG, get a 25-35% smaller WebP. No account, no watermark, no install needed." },
  { slug: "jpeg-to-webp", canonical: "jpg-to-webp", seoTitle: "Free JPEG to WebP Converter — Smaller Files", seoDescription: "Convert JPEG to WebP online free. 25-35% smaller files with the same visual quality. No signup, instant.", keywords: ["jpeg to webp", "convert jpeg to webp", "jpeg webp converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to WebP", h1Suffix: "for free.", eyebrow: "Free JPEG to WebP Converter — smaller files", heroSubline: "Upload any JPEG and get a smaller WebP in seconds. No signup, no watermark, browser-based." },
  { slug: "free-jpg-to-webp-converter", canonical: "jpg-to-webp", seoTitle: "Free JPG to WebP Converter — No Watermark", seoDescription: "Free online JPG to WebP converter. No watermark, no signup. Download smaller, faster WebP images.", keywords: ["free jpg to webp converter", "jpg to webp free"], h1Prefix: "Free", h1Highlight: "JPG to WebP converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free JPG to WebP converter online. No watermark ever, no account required." },
  { slug: "jpg-webp-converter-online", canonical: "jpg-to-webp", seoTitle: "JPG to WebP Converter Online — Fast & Free", seoDescription: "Online JPG to WebP converter. Fast, free, no signup. Reduce image file size by converting to WebP.", keywords: ["jpg webp converter online", "jpg to webp converter online"], h1Prefix: "The fast", h1Highlight: "JPG to WebP converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to WebP", heroSubline: "Convert any JPG to a smaller WebP in seconds, right in your browser." },
  { slug: "change-jpg-to-webp", canonical: "jpg-to-webp", seoTitle: "Change JPG to WebP Online Free — No App", seoDescription: "Change JPG images to WebP format online. No app, no signup, instant. Smaller files, faster websites.", keywords: ["change jpg to webp", "how to convert jpg to webp"], h1Prefix: "Change", h1Highlight: "JPG to WebP", h1Suffix: "on any device.", eyebrow: "Change JPG to WebP — no app install needed", heroSubline: "Change any JPG to WebP online, free. Smaller files for faster loading websites." },

  // ═══════════════════════ png-to-webp ═══════════════════════
  { slug: "convert-png-to-webp", canonical: "png-to-webp", seoTitle: "Convert PNG to WebP Online Free — Smaller", seoDescription: "Convert PNG to WebP online free. Cut file size by 26%+ with lossless WebP. No signup, instant.", keywords: ["convert png to webp", "convert png to webp online"], h1Prefix: "Convert", h1Highlight: "PNG to WebP", h1Suffix: "online, free.", eyebrow: "PNG to WebP Converter — smaller, faster files", heroSubline: "Upload a PNG, get a 26%+ smaller WebP. No account, no watermark, no install needed." },
  { slug: "free-png-to-webp-converter", canonical: "png-to-webp", seoTitle: "Free PNG to WebP Converter — No Watermark", seoDescription: "Free online PNG to WebP converter. No watermark, no signup. Download smaller WebP images instantly.", keywords: ["free png to webp converter", "png to webp free"], h1Prefix: "Free", h1Highlight: "PNG to WebP converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to WebP converter online. No watermark ever, no account required." },
  { slug: "png-webp-converter-online", canonical: "png-to-webp", seoTitle: "PNG to WebP Converter Online — Fast & Free", seoDescription: "Online PNG to WebP converter. Fast, free, no signup. Convert PNG images to next-gen WebP format.", keywords: ["png webp converter online", "png to webp converter online"], h1Prefix: "The fast", h1Highlight: "PNG to WebP converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to WebP", heroSubline: "Convert any PNG to a smaller WebP in seconds, right in your browser." },
  { slug: "change-png-to-webp", canonical: "png-to-webp", seoTitle: "Change PNG to WebP Online Free — No App", seoDescription: "Change PNG images to WebP format online. No app, no signup, instant. Works on any device.", keywords: ["change png to webp", "how to convert png to webp"], h1Prefix: "Change", h1Highlight: "PNG to WebP", h1Suffix: "on any device.", eyebrow: "Change PNG to WebP — no app install needed", heroSubline: "Change any PNG to WebP online, free. Works on iPhone, Android, Mac, and Windows." },
  { slug: "png-to-webp-transparent", canonical: "png-to-webp", seoTitle: "PNG to WebP — Transparency Preserved", seoDescription: "Convert PNG to WebP online free with transparency preserved. No signup, instant download, browser-based.", keywords: ["png to webp transparent", "png to webp with transparency"], h1Prefix: "Convert PNG to WebP with", h1Highlight: "transparency preserved", h1Suffix: ".", eyebrow: "PNG to WebP — alpha channel preserved", heroSubline: "Keep every transparent pixel intact when converting PNG to WebP. No signup, no watermark." },

  // ═══════════════════════ heic-to-jpg ═══════════════════════
  { slug: "convert-heic-to-jpg", canonical: "heic-to-jpg", seoTitle: "Convert HEIC to JPG Online Free — iPhone", seoDescription: "Convert iPhone HEIC photos to JPG online free. Instant download, no signup. Open on any device.", keywords: ["convert heic to jpg", "heic to jpg online", "iphone heic to jpg"], h1Prefix: "Convert", h1Highlight: "HEIC to JPG", h1Suffix: "online, free.", eyebrow: "HEIC to JPG Converter — for iPhone photos", heroSubline: "Upload an HEIC photo, get a universal JPG. No account, no watermark, no install needed." },
  { slug: "heic-to-jpeg", canonical: "heic-to-jpg", seoTitle: "Free HEIC to JPEG Converter — iPhone Photos", seoDescription: "Convert HEIC to JPEG online free. Open iPhone photos on Windows and Android. No signup, instant download.", keywords: ["heic to jpeg", "convert heic to jpeg", "heic jpeg converter online"], h1Prefix: "Convert", h1Highlight: "HEIC to JPEG", h1Suffix: "for free.", eyebrow: "Free HEIC to JPEG Converter — no signup", heroSubline: "Upload any HEIC photo and get a JPEG in seconds. No signup, no watermark, browser-based." },
  { slug: "free-heic-to-jpg-converter", canonical: "heic-to-jpg", seoTitle: "Free HEIC to JPG Converter — No App", seoDescription: "Free HEIC to JPG converter online. No app, no signup, no upload. Convert iPhone photos in your browser.", keywords: ["free heic to jpg converter", "heic to jpg free"], h1Prefix: "Free", h1Highlight: "HEIC to JPG converter", h1Suffix: "— no app needed.", eyebrow: "Zero app, zero signup — just convert", heroSubline: "The cleanest free HEIC to JPG converter online. No app install ever, no account required." },
  { slug: "iphone-heic-to-jpg", canonical: "heic-to-jpg", seoTitle: "iPhone HEIC to JPG Converter — Free Online", seoDescription: "Convert iPhone HEIC photos to JPG online for free. Works on Windows, Mac, and Android. No signup needed.", keywords: ["iphone heic to jpg", "open iphone photos on windows", "heic jpg iphone"], h1Prefix: "Convert", h1Highlight: "iPhone HEIC photos", h1Suffix: "to JPG.", eyebrow: "iPhone HEIC to JPG — works on any device", heroSubline: "Open your iPhone photos anywhere. Convert HEIC to JPG free, no signup, no app install." },
  { slug: "change-heic-to-jpg", canonical: "heic-to-jpg", seoTitle: "Change HEIC to JPG Online Free — No App", seoDescription: "Change iPhone HEIC images to JPG format online. No app, no signup, instant conversion. Any device.", keywords: ["change heic to jpg", "how to change heic to jpg"], h1Prefix: "Change", h1Highlight: "HEIC to JPG", h1Suffix: "on any device.", eyebrow: "Change HEIC to JPG — no app install needed", heroSubline: "Change any HEIC photo to JPG online, free. Works on Windows, Mac, and Android." },

  // ═══════════════════════ heic-to-png ═══════════════════════
  { slug: "convert-heic-to-png", canonical: "heic-to-png", seoTitle: "Convert HEIC to PNG Online Free — Lossless", seoDescription: "Convert iPhone HEIC photos to PNG online. Free, lossless output, no signup, instant download.", keywords: ["convert heic to png", "heic to png online", "iphone heic to png"], h1Prefix: "Convert", h1Highlight: "HEIC to PNG", h1Suffix: "online, free.", eyebrow: "HEIC to PNG Converter — lossless output", heroSubline: "Upload an HEIC photo, get a lossless PNG. No account, no watermark, no install needed." },
  { slug: "free-heic-to-png-converter", canonical: "heic-to-png", seoTitle: "Free HEIC to PNG Converter — No App", seoDescription: "Free HEIC to PNG converter online. Lossless output, no signup, no upload. Convert in your browser.", keywords: ["free heic to png converter", "heic to png free"], h1Prefix: "Free", h1Highlight: "HEIC to PNG converter", h1Suffix: "— no app needed.", eyebrow: "Zero app, zero signup — just convert", heroSubline: "The cleanest free HEIC to PNG converter online. No app install ever, no account required." },
  { slug: "heic-to-png-transparent", canonical: "heic-to-png", seoTitle: "HEIC to PNG Converter — Lossless Online", seoDescription: "Convert HEIC to PNG online free. Lossless quality for editing and printing. No signup, browser-based.", keywords: ["heic to png lossless", "heic to transparent png"], h1Prefix: "Convert HEIC to PNG with", h1Highlight: "lossless quality", h1Suffix: ".", eyebrow: "HEIC to PNG — every pixel preserved", heroSubline: "Get a perfect lossless PNG from any iPhone HEIC photo. No signup, no watermark." },
  { slug: "iphone-heic-to-png", canonical: "heic-to-png", seoTitle: "iPhone HEIC to PNG Converter — Free Online", seoDescription: "Convert iPhone HEIC photos to lossless PNG online for free. No signup, no app. Works on any device.", keywords: ["iphone heic to png", "iphone photos to png"], h1Prefix: "Convert", h1Highlight: "iPhone HEIC photos", h1Suffix: "to PNG.", eyebrow: "iPhone HEIC to PNG — lossless quality", heroSubline: "Turn your iPhone photos into lossless PNGs. Free, no signup, no app install." },
  { slug: "change-heic-to-png", canonical: "heic-to-png", seoTitle: "Change HEIC to PNG Online Free — No App", seoDescription: "Change iPhone HEIC images to PNG format online. No app, no signup, instant conversion.", keywords: ["change heic to png", "how to change heic to png"], h1Prefix: "Change", h1Highlight: "HEIC to PNG", h1Suffix: "on any device.", eyebrow: "Change HEIC to PNG — no app install needed", heroSubline: "Change any HEIC photo to lossless PNG online, free. Works on Windows, Mac, and Android." },

  // ═══════════════════════ svg-to-png ═══════════════════════
  { slug: "convert-svg-to-png", canonical: "svg-to-png", seoTitle: "Convert SVG to PNG Online Free — Hi-Res", seoDescription: "Convert SVG vector to PNG online. Free, high resolution, no signup, instant download. Browser-based.", keywords: ["convert svg to png", "svg to png online", "svg to png converter"], h1Prefix: "Convert", h1Highlight: "SVG to PNG", h1Suffix: "online, free.", eyebrow: "SVG to PNG Converter — high resolution", heroSubline: "Upload an SVG, get a crisp high-resolution PNG. No account, no watermark, no install needed." },
  { slug: "free-svg-to-png-converter", canonical: "svg-to-png", seoTitle: "Free SVG to PNG Converter — No Watermark", seoDescription: "Free SVG to PNG converter online. High-resolution raster output, no watermark, no signup.", keywords: ["free svg to png converter", "svg to png free"], h1Prefix: "Free", h1Highlight: "SVG to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free SVG to PNG converter online. No watermark ever, no account required." },
  { slug: "svg-to-png-high-resolution", canonical: "svg-to-png", seoTitle: "SVG to PNG High Resolution Converter", seoDescription: "Convert SVG to high-resolution PNG online free. No signup, no watermark. Perfect for logos and icons.", keywords: ["svg to png high resolution", "svg to png hd", "svg to high res png"], h1Prefix: "Render SVG at", h1Highlight: "high resolution", h1Suffix: "PNG.", eyebrow: "SVG to PNG — sharp at any resolution", heroSubline: "Get crisp, high-resolution PNG output from any SVG vector. Ideal for logos and icons." },
  { slug: "svg-png-converter-online", canonical: "svg-to-png", seoTitle: "SVG to PNG Converter Online — Fast & Free", seoDescription: "Online SVG to PNG converter. Fast, free, no signup. Render your SVG as a high-quality PNG raster image.", keywords: ["svg png converter online", "svg to png converter online"], h1Prefix: "The fast", h1Highlight: "SVG to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based SVG to PNG", heroSubline: "Render any SVG as a high-quality PNG in seconds, right in your browser." },
  { slug: "change-svg-to-png", canonical: "svg-to-png", seoTitle: "Change SVG to PNG Online Free — No App", seoDescription: "Change SVG vector files to PNG raster format online. No app, no signup, instant conversion.", keywords: ["change svg to png", "how to convert svg to png"], h1Prefix: "Change", h1Highlight: "SVG to PNG", h1Suffix: "on any device.", eyebrow: "Change SVG to PNG — no app install needed", heroSubline: "Change any SVG vector to a raster PNG online, free. Works on any device." },

  // ═══════════════════════ gif-to-jpg ═══════════════════════
  { slug: "convert-gif-to-jpg", canonical: "gif-to-jpg", seoTitle: "Convert GIF to JPG Online Free — Frame", seoDescription: "Convert GIF to JPG online. Free, no signup, instant. Extracts the first frame as a static JPG.", keywords: ["convert gif to jpg", "gif to jpg online", "gif frame to jpg"], h1Prefix: "Convert", h1Highlight: "GIF to JPG", h1Suffix: "online, free.", eyebrow: "GIF to JPG Converter — extract first frame", heroSubline: "Upload a GIF, get a static JPG of the first frame. No account, no watermark, no install needed." },
  { slug: "gif-to-jpeg", canonical: "gif-to-jpg", seoTitle: "Free GIF to JPEG Converter — No Signup", seoDescription: "Convert GIF to JPEG online free. Extract the first frame as a static JPEG. No signup, instant download.", keywords: ["gif to jpeg", "convert gif to jpeg", "gif jpeg converter online"], h1Prefix: "Convert", h1Highlight: "GIF to JPEG", h1Suffix: "for free.", eyebrow: "Free GIF to JPEG Converter — no signup", heroSubline: "Upload any GIF and get a JPEG of the first frame. No signup, no watermark, browser-based." },
  { slug: "free-gif-to-jpg-converter", canonical: "gif-to-jpg", seoTitle: "Free GIF to JPG Converter — No Watermark", seoDescription: "Free GIF to JPG converter online. Extract GIF frames as JPG images. No watermark, no signup.", keywords: ["free gif to jpg converter", "gif to jpg free"], h1Prefix: "Free", h1Highlight: "GIF to JPG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free GIF to JPG converter online. No watermark ever, no account required." },
  { slug: "gif-jpg-converter-online", canonical: "gif-to-jpg", seoTitle: "GIF to JPG Converter Online — Fast & Free", seoDescription: "Online GIF to JPG converter. Fast, free, no signup. Convert any GIF to a static JPG image.", keywords: ["gif jpg converter online", "gif to jpg converter online"], h1Prefix: "The fast", h1Highlight: "GIF to JPG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based GIF to JPG", heroSubline: "Convert any GIF frame to JPG in seconds, right in your browser." },
  { slug: "gif-frame-to-jpg", canonical: "gif-to-jpg", seoTitle: "GIF Frame to JPG Converter Free Online", seoDescription: "Extract any GIF frame and convert to JPG online free. No signup, instant download, browser-based.", keywords: ["gif frame to jpg", "extract gif frame jpg", "gif to jpg first frame"], h1Prefix: "Extract a", h1Highlight: "GIF frame as JPG", h1Suffix: ".", eyebrow: "GIF Frame Extractor — save as static JPG", heroSubline: "Pull a still frame out of any GIF and save it as a JPG. No signup, no watermark." },

  // ═══════════════════════ gif-to-png ═══════════════════════
  { slug: "convert-gif-to-png", canonical: "gif-to-png", seoTitle: "Convert GIF to PNG Online Free — Lossless", seoDescription: "Convert GIF to PNG online. Free, lossless output, no signup, instant download.", keywords: ["convert gif to png", "gif to png online"], h1Prefix: "Convert", h1Highlight: "GIF to PNG", h1Suffix: "online, free.", eyebrow: "GIF to PNG Converter — lossless output", heroSubline: "Upload a GIF, get a lossless PNG of the first frame. No account, no watermark, no install needed." },
  { slug: "free-gif-to-png-converter", canonical: "gif-to-png", seoTitle: "Free GIF to PNG Converter — No Watermark", seoDescription: "Free GIF to PNG converter online. Lossless output, no watermark, no signup. Browser-based.", keywords: ["free gif to png converter", "gif to png free"], h1Prefix: "Free", h1Highlight: "GIF to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free GIF to PNG converter online. No watermark ever, no account required." },
  { slug: "gif-png-converter-online", canonical: "gif-to-png", seoTitle: "GIF to PNG Converter Online — Fast & Free", seoDescription: "Online GIF to PNG converter. Fast, free, no signup. Extract GIF frames as lossless PNG images.", keywords: ["gif png converter online", "gif to png converter online"], h1Prefix: "The fast", h1Highlight: "GIF to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based GIF to PNG", heroSubline: "Convert any GIF frame to lossless PNG in seconds, right in your browser." },
  { slug: "gif-frame-to-png", canonical: "gif-to-png", seoTitle: "GIF Frame to PNG Converter Free Online", seoDescription: "Extract GIF frames as PNG images online free. Lossless quality, no signup, instant download.", keywords: ["gif frame to png", "extract gif frame png"], h1Prefix: "Extract a", h1Highlight: "GIF frame as PNG", h1Suffix: ".", eyebrow: "GIF Frame Extractor — save as lossless PNG", heroSubline: "Pull a still frame out of any GIF and save it as a lossless PNG. No signup, no watermark." },
  { slug: "change-gif-to-png", canonical: "gif-to-png", seoTitle: "Change GIF to PNG Online Free — No App", seoDescription: "Change GIF images to PNG format online. No app, no signup, instant. Lossless output.", keywords: ["change gif to png", "how to convert gif to png"], h1Prefix: "Change", h1Highlight: "GIF to PNG", h1Suffix: "on any device.", eyebrow: "Change GIF to PNG — no app install needed", heroSubline: "Change any GIF to a lossless PNG online, free. Works on any device." },

  // ═══════════════════════ gif-to-webp ═══════════════════════
  { slug: "convert-gif-to-webp", canonical: "gif-to-webp", seoTitle: "Convert GIF to WebP Online Free — Smaller", seoDescription: "Convert GIF to WebP online. Free, no signup, instant. Get smaller animated files for faster loading.", keywords: ["convert gif to webp", "gif to webp online", "animated gif to webp"], h1Prefix: "Convert", h1Highlight: "GIF to WebP", h1Suffix: "online, free.", eyebrow: "GIF to WebP Converter — smaller animated files", heroSubline: "Upload a GIF, get a smaller WebP. No account, no watermark, no install needed." },
  { slug: "free-gif-to-webp-converter", canonical: "gif-to-webp", seoTitle: "Free GIF to WebP Converter — No Watermark", seoDescription: "Free GIF to WebP converter online. Smaller files, no watermark, no signup. Browser-based conversion.", keywords: ["free gif to webp converter", "gif to webp free"], h1Prefix: "Free", h1Highlight: "GIF to WebP converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free GIF to WebP converter online. No watermark ever, no account required." },
  { slug: "gif-webp-converter-online", canonical: "gif-to-webp", seoTitle: "GIF to WebP Converter Online — Fast & Free", seoDescription: "Online GIF to WebP converter. Fast, free, no signup. Convert GIFs to smaller WebP format.", keywords: ["gif webp converter online", "gif to webp converter online"], h1Prefix: "The fast", h1Highlight: "GIF to WebP converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based GIF to WebP", heroSubline: "Convert any GIF to a smaller WebP in seconds, right in your browser." },
  { slug: "animated-gif-to-webp", canonical: "gif-to-webp", seoTitle: "Animated GIF to WebP Converter Free", seoDescription: "Convert animated GIFs to WebP online free. Smaller files with better quality. No signup, instant download.", keywords: ["animated gif to webp", "convert animated gif to webp"], h1Prefix: "Convert", h1Highlight: "animated GIFs to WebP", h1Suffix: ".", eyebrow: "Animated GIF to WebP — smaller, same quality", heroSubline: "Shrink your animated GIFs into efficient WebP files. No signup, no watermark." },
  { slug: "change-gif-to-webp", canonical: "gif-to-webp", seoTitle: "Change GIF to WebP Online Free — No App", seoDescription: "Change GIF images to WebP format online. No app, no signup, instant. Smaller, faster files.", keywords: ["change gif to webp", "how to convert gif to webp"], h1Prefix: "Change", h1Highlight: "GIF to WebP", h1Suffix: "on any device.", eyebrow: "Change GIF to WebP — no app install needed", heroSubline: "Change any GIF to a smaller WebP online, free. Works on any device." },

  // ═══════════════════════ bmp-to-jpg ═══════════════════════
  { slug: "convert-bmp-to-jpg", canonical: "bmp-to-jpg", seoTitle: "Convert BMP to JPG Online Free — Reduce Size", seoDescription: "Convert BMP to JPG online free. Reduce BMP file size by 90%+. No signup, instant download.", keywords: ["convert bmp to jpg", "bmp to jpg online", "bmp to jpeg online"], h1Prefix: "Convert", h1Highlight: "BMP to JPG", h1Suffix: "online, free.", eyebrow: "BMP to JPG Converter — 90%+ smaller files", heroSubline: "Upload a BMP, get a 90%+ smaller JPG. No account, no watermark, no install needed." },
  { slug: "bmp-to-jpeg", canonical: "bmp-to-jpg", seoTitle: "Free BMP to JPEG Converter — Reduce Size", seoDescription: "Convert BMP to JPEG online free. Reduce large bitmap files by 90%+. No signup, instant download.", keywords: ["bmp to jpeg", "convert bmp to jpeg", "bmp jpeg converter online"], h1Prefix: "Convert", h1Highlight: "BMP to JPEG", h1Suffix: "for free.", eyebrow: "Free BMP to JPEG Converter — no signup", heroSubline: "Upload any BMP and get a compact JPEG in seconds. No signup, no watermark, browser-based." },
  { slug: "free-bmp-to-jpg-converter", canonical: "bmp-to-jpg", seoTitle: "Free BMP to JPG Converter — No Watermark", seoDescription: "Free BMP to JPG converter online. No watermark, no signup. Dramatically reduce bitmap file sizes.", keywords: ["free bmp to jpg converter", "bmp to jpg free"], h1Prefix: "Free", h1Highlight: "BMP to JPG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free BMP to JPG converter online. No watermark ever, no account required." },
  { slug: "bmp-jpg-converter-online", canonical: "bmp-to-jpg", seoTitle: "BMP to JPG Converter Online — Fast & Free", seoDescription: "Online BMP to JPG converter. Fast, free, no signup. Convert large BMP files to compact JPGs.", keywords: ["bmp jpg converter online", "bmp to jpg converter online"], h1Prefix: "The fast", h1Highlight: "BMP to JPG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based BMP to JPG", heroSubline: "Convert any BMP to a compact JPG in seconds, right in your browser." },
  { slug: "change-bmp-to-jpg", canonical: "bmp-to-jpg", seoTitle: "Change BMP to JPG Online Free — No App", seoDescription: "Change BMP bitmap images to JPG format online. No app, no signup, instant. 90%+ size reduction.", keywords: ["change bmp to jpg", "how to convert bmp to jpg"], h1Prefix: "Change", h1Highlight: "BMP to JPG", h1Suffix: "on any device.", eyebrow: "Change BMP to JPG — no app install needed", heroSubline: "Change any BMP to a smaller JPG online, free. 90%+ file size reduction." },

  // ═══════════════════════ bmp-to-png ═══════════════════════
  { slug: "convert-bmp-to-png", canonical: "bmp-to-png", seoTitle: "Convert BMP to PNG Online Free — Lossless", seoDescription: "Convert BMP to PNG online. Free, lossless compression, no signup, instant download.", keywords: ["convert bmp to png", "bmp to png online"], h1Prefix: "Convert", h1Highlight: "BMP to PNG", h1Suffix: "online, free.", eyebrow: "BMP to PNG Converter — lossless output", heroSubline: "Upload a BMP, get a lossless PNG. No account, no watermark, no install needed." },
  { slug: "free-bmp-to-png-converter", canonical: "bmp-to-png", seoTitle: "Free BMP to PNG Converter — No Watermark", seoDescription: "Free BMP to PNG converter online. Lossless compression, no watermark, no signup. Browser-based.", keywords: ["free bmp to png converter", "bmp to png free"], h1Prefix: "Free", h1Highlight: "BMP to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free BMP to PNG converter online. No watermark ever, no account required." },
  { slug: "bmp-png-converter-online", canonical: "bmp-to-png", seoTitle: "BMP to PNG Converter Online — Fast & Free", seoDescription: "Online BMP to PNG converter. Fast, free, no signup. Lossless PNG output from BMP bitmaps.", keywords: ["bmp png converter online", "bmp to png converter online"], h1Prefix: "The fast", h1Highlight: "BMP to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based BMP to PNG", heroSubline: "Convert any BMP to lossless PNG in seconds, right in your browser." },
  { slug: "bitmap-to-png", canonical: "bmp-to-png", seoTitle: "Bitmap to PNG Converter Free Online", seoDescription: "Convert bitmap (BMP) images to PNG online free. Lossless compression, no signup, instant download.", keywords: ["bitmap to png", "convert bitmap to png", "bmp bitmap to png"], h1Prefix: "Convert", h1Highlight: "bitmap to PNG", h1Suffix: "free.", eyebrow: "Bitmap to PNG — lossless compression", heroSubline: "Convert bitmap images to compressed lossless PNG files. No signup, no watermark." },
  { slug: "change-bmp-to-png", canonical: "bmp-to-png", seoTitle: "Change BMP to PNG Online Free — No App", seoDescription: "Change BMP bitmap images to PNG format online. No app, no signup, instant. Lossless output.", keywords: ["change bmp to png", "how to convert bmp to png"], h1Prefix: "Change", h1Highlight: "BMP to PNG", h1Suffix: "on any device.", eyebrow: "Change BMP to PNG — no app install needed", heroSubline: "Change any BMP bitmap to a lossless PNG online, free. Works on any device." },

  // ═══════════════════════ tiff-to-jpg ═══════════════════════
  { slug: "convert-tiff-to-jpg", canonical: "tiff-to-jpg", seoTitle: "Convert TIFF to JPG Online Free — Smaller", seoDescription: "Convert TIFF to JPG online. Free, no signup, instant. Reduce large TIFF files for web sharing.", keywords: ["convert tiff to jpg", "tiff to jpg online", "tif to jpg"], h1Prefix: "Convert", h1Highlight: "TIFF to JPG", h1Suffix: "online, free.", eyebrow: "TIFF to JPG Converter — smaller web-ready files", heroSubline: "Upload a TIFF, get a compact JPG. No account, no watermark, no install needed." },
  { slug: "tiff-to-jpeg", canonical: "tiff-to-jpg", seoTitle: "Free TIFF to JPEG Converter — Reduce Size", seoDescription: "Convert TIFF to JPEG online free. Reduce large TIFF files for easy sharing. No signup, instant download.", keywords: ["tiff to jpeg", "convert tiff to jpeg", "tiff jpeg converter online"], h1Prefix: "Convert", h1Highlight: "TIFF to JPEG", h1Suffix: "for free.", eyebrow: "Free TIFF to JPEG Converter — no signup", heroSubline: "Upload any TIFF and get a compact JPEG in seconds. No signup, no watermark, browser-based." },
  { slug: "tif-to-jpg", canonical: "tiff-to-jpg", seoTitle: "Free TIF to JPG Converter Online", seoDescription: "Convert TIF files to JPG online free. No signup, instant download. Works for both .tif and .tiff files.", keywords: ["tif to jpg", "convert tif to jpg", "tif to jpg converter"], h1Prefix: "Convert", h1Highlight: "TIF to JPG", h1Suffix: "free.", eyebrow: "TIF to JPG Converter — .tif and .tiff supported", heroSubline: "Convert any TIF or TIFF file to a compact JPG. No signup, no watermark, browser-based." },
  { slug: "tiff-jpg-converter-online", canonical: "tiff-to-jpg", seoTitle: "TIFF to JPG Converter Online — Fast & Free", seoDescription: "Online TIFF to JPG converter. Fast, free, no signup. Compress large TIFF files to compact JPGs.", keywords: ["tiff jpg converter online", "tiff to jpg converter online"], h1Prefix: "The fast", h1Highlight: "TIFF to JPG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based TIFF to JPG", heroSubline: "Convert any TIFF to a compact JPG in seconds, right in your browser." },
  { slug: "change-tiff-to-jpg", canonical: "tiff-to-jpg", seoTitle: "Change TIFF to JPG Online Free — No App", seoDescription: "Change TIFF images to JPG format online. No app, no signup, instant. Works on any device.", keywords: ["change tiff to jpg", "how to convert tiff to jpg"], h1Prefix: "Change", h1Highlight: "TIFF to JPG", h1Suffix: "on any device.", eyebrow: "Change TIFF to JPG — no app install needed", heroSubline: "Change any TIFF to JPG online, free. Works on iPhone, Android, Mac, and Windows." },

  // ═══════════════════════ tiff-to-png ═══════════════════════
  { slug: "convert-tiff-to-png", canonical: "tiff-to-png", seoTitle: "Convert TIFF to PNG Online Free — Lossless", seoDescription: "Convert TIFF to PNG online. Free, lossless output, no signup, instant download.", keywords: ["convert tiff to png", "tiff to png online", "tif to png"], h1Prefix: "Convert", h1Highlight: "TIFF to PNG", h1Suffix: "online, free.", eyebrow: "TIFF to PNG Converter — lossless output", heroSubline: "Upload a TIFF, get a lossless PNG. No account, no watermark, no install needed." },
  { slug: "tif-to-png", canonical: "tiff-to-png", seoTitle: "Free TIF to PNG Converter Online", seoDescription: "Convert TIF files to PNG online free. Lossless output, no signup, instant download. Works for .tif and .tiff.", keywords: ["tif to png", "convert tif to png", "tif to png converter"], h1Prefix: "Convert", h1Highlight: "TIF to PNG", h1Suffix: "free.", eyebrow: "TIF to PNG Converter — .tif and .tiff supported", heroSubline: "Convert any TIF or TIFF file to a lossless PNG. No signup, no watermark, browser-based." },
  { slug: "free-tiff-to-png-converter", canonical: "tiff-to-png", seoTitle: "Free TIFF to PNG Converter — No Watermark", seoDescription: "Free TIFF to PNG converter online. Lossless compression, no watermark, no signup. Browser-based.", keywords: ["free tiff to png converter", "tiff to png free"], h1Prefix: "Free", h1Highlight: "TIFF to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free TIFF to PNG converter online. No watermark ever, no account required." },
  { slug: "tiff-png-converter-online", canonical: "tiff-to-png", seoTitle: "TIFF to PNG Converter Online — Fast & Free", seoDescription: "Online TIFF to PNG converter. Fast, free, no signup. Lossless PNG output from TIFF images.", keywords: ["tiff png converter online", "tiff to png converter online"], h1Prefix: "The fast", h1Highlight: "TIFF to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based TIFF to PNG", heroSubline: "Convert any TIFF to lossless PNG in seconds, right in your browser." },
  { slug: "change-tiff-to-png", canonical: "tiff-to-png", seoTitle: "Change TIFF to PNG Online Free — No App", seoDescription: "Change TIFF images to PNG format online. No app, no signup, instant. Lossless output.", keywords: ["change tiff to png", "how to convert tiff to png"], h1Prefix: "Change", h1Highlight: "TIFF to PNG", h1Suffix: "on any device.", eyebrow: "Change TIFF to PNG — no app install needed", heroSubline: "Change any TIFF to a lossless PNG online, free. Works on any device." },

  // ═══════════════════════ jpg-to-avif ═══════════════════════
  { slug: "convert-jpg-to-avif", canonical: "jpg-to-avif", seoTitle: "Convert JPG to AVIF Online Free — Next-Gen", seoDescription: "Convert JPG to AVIF online free. Get 50% smaller files with better quality. No signup, instant.", keywords: ["convert jpg to avif", "jpg to avif online"], h1Prefix: "Convert", h1Highlight: "JPG to AVIF", h1Suffix: "online, free.", eyebrow: "JPG to AVIF Converter — 50% smaller files", heroSubline: "Upload a JPG, get a 50% smaller AVIF. No account, no watermark, no install needed." },
  { slug: "jpeg-to-avif", canonical: "jpg-to-avif", seoTitle: "Free JPEG to AVIF Converter — Smaller Files", seoDescription: "Convert JPEG to AVIF online free. 50% smaller than JPG with the same quality. No signup, instant.", keywords: ["jpeg to avif", "convert jpeg to avif", "jpeg avif converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to AVIF", h1Suffix: "for free.", eyebrow: "Free JPEG to AVIF Converter — next-gen format", heroSubline: "Upload any JPEG and get a dramatically smaller AVIF. No signup, no watermark, browser-based." },
  { slug: "free-jpg-to-avif-converter", canonical: "jpg-to-avif", seoTitle: "Free JPG to AVIF Converter — No Watermark", seoDescription: "Free JPG to AVIF converter online. No watermark, no signup. Convert to next-gen AVIF format instantly.", keywords: ["free jpg to avif converter", "jpg to avif free"], h1Prefix: "Free", h1Highlight: "JPG to AVIF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free JPG to AVIF converter online. No watermark ever, no account required." },
  { slug: "jpg-avif-converter-online", canonical: "jpg-to-avif", seoTitle: "JPG to AVIF Converter Online — Fast & Free", seoDescription: "Online JPG to AVIF converter. Fast, free, no signup. Upgrade to next-gen AVIF format.", keywords: ["jpg avif converter online", "jpg to avif converter online"], h1Prefix: "The fast", h1Highlight: "JPG to AVIF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to AVIF", heroSubline: "Convert any JPG to next-gen AVIF in seconds, right in your browser." },
  { slug: "change-jpg-to-avif", canonical: "jpg-to-avif", seoTitle: "Change JPG to AVIF Online Free — No App", seoDescription: "Change JPG images to AVIF next-gen format online. No app, no signup, instant. 50% smaller files.", keywords: ["change jpg to avif", "how to convert jpg to avif"], h1Prefix: "Change", h1Highlight: "JPG to AVIF", h1Suffix: "on any device.", eyebrow: "Change JPG to AVIF — no app install needed", heroSubline: "Change any JPG to next-gen AVIF online, free. 50% smaller files." },

  // ═══════════════════════ png-to-avif ═══════════════════════
  { slug: "convert-png-to-avif", canonical: "png-to-avif", seoTitle: "Convert PNG to AVIF Online Free — Smallest", seoDescription: "Convert PNG to AVIF online free. Dramatically reduce file size with next-gen compression. No signup.", keywords: ["convert png to avif", "png to avif online"], h1Prefix: "Convert", h1Highlight: "PNG to AVIF", h1Suffix: "online, free.", eyebrow: "PNG to AVIF Converter — smallest files", heroSubline: "Upload a PNG, get a dramatically smaller AVIF. No account, no watermark, no install needed." },
  { slug: "free-png-to-avif-converter", canonical: "png-to-avif", seoTitle: "Free PNG to AVIF Converter — No Watermark", seoDescription: "Free PNG to AVIF converter online. No watermark, no signup. Get the smallest possible web images.", keywords: ["free png to avif converter", "png to avif free"], h1Prefix: "Free", h1Highlight: "PNG to AVIF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to AVIF converter online. No watermark ever, no account required." },
  { slug: "png-avif-converter-online", canonical: "png-to-avif", seoTitle: "PNG to AVIF Converter Online — Fast & Free", seoDescription: "Online PNG to AVIF converter. Fast, free, no signup. Convert PNG to next-gen AVIF format.", keywords: ["png avif converter online", "png to avif converter online"], h1Prefix: "The fast", h1Highlight: "PNG to AVIF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to AVIF", heroSubline: "Convert any PNG to next-gen AVIF in seconds, right in your browser." },
  { slug: "png-to-avif-transparent", canonical: "png-to-avif", seoTitle: "PNG to AVIF — Transparency Supported", seoDescription: "Convert PNG to AVIF online free with transparency support. No signup, instant download.", keywords: ["png to avif transparent", "png to avif alpha"], h1Prefix: "Convert PNG to AVIF with", h1Highlight: "transparency supported", h1Suffix: ".", eyebrow: "PNG to AVIF — alpha channel preserved", heroSubline: "Keep transparency when converting PNG to next-gen AVIF. No signup, no watermark." },
  { slug: "change-png-to-avif", canonical: "png-to-avif", seoTitle: "Change PNG to AVIF Online Free — No App", seoDescription: "Change PNG images to AVIF format online. No app, no signup, instant. Smallest file sizes for web.", keywords: ["change png to avif", "how to convert png to avif"], h1Prefix: "Change", h1Highlight: "PNG to AVIF", h1Suffix: "on any device.", eyebrow: "Change PNG to AVIF — no app install needed", heroSubline: "Change any PNG to next-gen AVIF online, free. The smallest files for the web." },

  // ═══════════════════════ webp-to-avif ═══════════════════════
  { slug: "convert-webp-to-avif", canonical: "webp-to-avif", seoTitle: "Convert WebP to AVIF Online Free — Smaller", seoDescription: "Convert WebP to AVIF online free. Get 20% smaller files than WebP. No signup, instant.", keywords: ["convert webp to avif", "webp to avif online"], h1Prefix: "Convert", h1Highlight: "WebP to AVIF", h1Suffix: "online, free.", eyebrow: "WebP to AVIF Converter — even smaller files", heroSubline: "Upload a WebP, get a 20% smaller AVIF. No account, no watermark, no install needed." },
  { slug: "free-webp-to-avif-converter", canonical: "webp-to-avif", seoTitle: "Free WebP to AVIF Converter — No Watermark", seoDescription: "Free WebP to AVIF converter online. No watermark, no signup. Upgrade to next-gen AVIF.", keywords: ["free webp to avif converter", "webp to avif free"], h1Prefix: "Free", h1Highlight: "WebP to AVIF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to AVIF converter online. No watermark ever, no account required." },
  { slug: "webp-avif-converter-online", canonical: "webp-to-avif", seoTitle: "WebP to AVIF Converter Online — Fast & Free", seoDescription: "Online WebP to AVIF converter. Fast, free, no signup. Get even smaller files than WebP.", keywords: ["webp avif converter online", "webp to avif converter online"], h1Prefix: "The fast", h1Highlight: "WebP to AVIF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to AVIF", heroSubline: "Convert any WebP to AVIF in seconds, right in your browser." },
  { slug: "upgrade-webp-to-avif", canonical: "webp-to-avif", seoTitle: "Upgrade WebP to AVIF Free — Better Compression", seoDescription: "Upgrade your WebP images to AVIF format online. 20% smaller files with the same quality. No signup.", keywords: ["upgrade webp to avif", "webp vs avif converter"], h1Prefix: "Upgrade", h1Highlight: "WebP to AVIF", h1Suffix: "— better compression.", eyebrow: "Upgrade from WebP to AVIF — 20% smaller", heroSubline: "Upgrade your WebP images to next-gen AVIF for 20% smaller files. Free, no signup." },
  { slug: "change-webp-to-avif", canonical: "webp-to-avif", seoTitle: "Change WebP to AVIF Online Free — No App", seoDescription: "Change WebP images to AVIF next-gen format online. No app, no signup, instant.", keywords: ["change webp to avif", "how to convert webp to avif"], h1Prefix: "Change", h1Highlight: "WebP to AVIF", h1Suffix: "on any device.", eyebrow: "Change WebP to AVIF — no app install needed", heroSubline: "Change any WebP to next-gen AVIF online, free. Even smaller than WebP." },

  // ═══════════════════════ avif-to-jpg ═══════════════════════
  { slug: "convert-avif-to-jpg", canonical: "avif-to-jpg", seoTitle: "Convert AVIF to JPG Online Free — Universal", seoDescription: "Convert AVIF to JPG online free. Make AVIF files compatible with all apps. No signup, instant.", keywords: ["convert avif to jpg", "avif to jpg online"], h1Prefix: "Convert", h1Highlight: "AVIF to JPG", h1Suffix: "online, free.", eyebrow: "AVIF to JPG Converter — universal compatibility", heroSubline: "Upload an AVIF, get a universally compatible JPG. No account, no watermark, no install needed." },
  { slug: "avif-to-jpeg", canonical: "avif-to-jpg", seoTitle: "Free AVIF to JPEG Converter — Universal", seoDescription: "Convert AVIF to JPEG online free. Open AVIF images in any app. No signup, instant download.", keywords: ["avif to jpeg", "convert avif to jpeg", "avif jpeg converter online"], h1Prefix: "Convert", h1Highlight: "AVIF to JPEG", h1Suffix: "for free.", eyebrow: "Free AVIF to JPEG Converter — no signup", heroSubline: "Upload any AVIF and get a universal JPEG in seconds. No signup, no watermark, browser-based." },
  { slug: "free-avif-to-jpg-converter", canonical: "avif-to-jpg", seoTitle: "Free AVIF to JPG Converter — No Watermark", seoDescription: "Free AVIF to JPG converter online. No watermark, no signup. Make AVIF files universally compatible.", keywords: ["free avif to jpg converter", "avif to jpg free"], h1Prefix: "Free", h1Highlight: "AVIF to JPG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free AVIF to JPG converter online. No watermark ever, no account required." },
  { slug: "avif-jpg-converter-online", canonical: "avif-to-jpg", seoTitle: "AVIF to JPG Converter Online — Fast & Free", seoDescription: "Online AVIF to JPG converter. Fast, free, no signup. Convert next-gen AVIF to universal JPG.", keywords: ["avif jpg converter online", "avif to jpg converter online"], h1Prefix: "The fast", h1Highlight: "AVIF to JPG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based AVIF to JPG", heroSubline: "Convert any AVIF to universal JPG in seconds, right in your browser." },
  { slug: "change-avif-to-jpg", canonical: "avif-to-jpg", seoTitle: "Change AVIF to JPG Online Free — No App", seoDescription: "Change AVIF images to JPG format online. No app, no signup, instant. Universal compatibility.", keywords: ["change avif to jpg", "how to convert avif to jpg"], h1Prefix: "Change", h1Highlight: "AVIF to JPG", h1Suffix: "on any device.", eyebrow: "Change AVIF to JPG — no app install needed", heroSubline: "Change any AVIF to a universal JPG online, free. Works on any device." },

  // ═══════════════════════ avif-to-png ═══════════════════════
  { slug: "convert-avif-to-png", canonical: "avif-to-png", seoTitle: "Convert AVIF to PNG Online Free — Lossless", seoDescription: "Convert AVIF to PNG online free. Lossless output, no signup, instant download.", keywords: ["convert avif to png", "avif to png online"], h1Prefix: "Convert", h1Highlight: "AVIF to PNG", h1Suffix: "online, free.", eyebrow: "AVIF to PNG Converter — lossless output", heroSubline: "Upload an AVIF, get a lossless PNG. No account, no watermark, no install needed." },
  { slug: "free-avif-to-png-converter", canonical: "avif-to-png", seoTitle: "Free AVIF to PNG Converter — No Watermark", seoDescription: "Free AVIF to PNG converter online. Lossless output, no watermark, no signup.", keywords: ["free avif to png converter", "avif to png free"], h1Prefix: "Free", h1Highlight: "AVIF to PNG converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free AVIF to PNG converter online. No watermark ever, no account required." },
  { slug: "avif-png-converter-online", canonical: "avif-to-png", seoTitle: "AVIF to PNG Converter Online — Fast & Free", seoDescription: "Online AVIF to PNG converter. Fast, free, no signup. Convert AVIF to lossless PNG.", keywords: ["avif png converter online", "avif to png converter online"], h1Prefix: "The fast", h1Highlight: "AVIF to PNG converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based AVIF to PNG", heroSubline: "Convert any AVIF to lossless PNG in seconds, right in your browser." },
  { slug: "avif-to-png-transparent", canonical: "avif-to-png", seoTitle: "AVIF to PNG — Transparency Preserved", seoDescription: "Convert AVIF to PNG online free with transparency preserved. No signup, instant download.", keywords: ["avif to png transparent", "avif to png alpha"], h1Prefix: "Convert AVIF to PNG with", h1Highlight: "transparency preserved", h1Suffix: ".", eyebrow: "AVIF to PNG — alpha channel preserved", heroSubline: "Keep transparency when converting AVIF to lossless PNG. No signup, no watermark." },
  { slug: "change-avif-to-png", canonical: "avif-to-png", seoTitle: "Change AVIF to PNG Online Free — No App", seoDescription: "Change AVIF images to PNG format online. No app, no signup, instant. Lossless quality.", keywords: ["change avif to png", "how to convert avif to png"], h1Prefix: "Change", h1Highlight: "AVIF to PNG", h1Suffix: "on any device.", eyebrow: "Change AVIF to PNG — no app install needed", heroSubline: "Change any AVIF to a lossless PNG online, free. Works on any device." },

  // ═══════════════════════ jpg-to-gif ═══════════════════════
  { slug: "convert-jpg-to-gif", canonical: "jpg-to-gif", seoTitle: "Convert JPG to GIF Online Free — Instant", seoDescription: "Convert JPG to GIF online free. Create static GIF images from JPG photos. No signup, instant download.", keywords: ["convert jpg to gif", "jpg to gif online"], h1Prefix: "Convert", h1Highlight: "JPG to GIF", h1Suffix: "online, free.", eyebrow: "JPG to GIF Converter — instant, browser-based", heroSubline: "Upload a JPG, get a GIF. No account, no watermark, no install needed." },
  { slug: "jpeg-to-gif", canonical: "jpg-to-gif", seoTitle: "Free JPEG to GIF Converter — No Signup", seoDescription: "Convert JPEG to GIF online free. No signup, instant download. Browser-based static GIF conversion.", keywords: ["jpeg to gif", "convert jpeg to gif", "jpeg gif converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to GIF", h1Suffix: "for free.", eyebrow: "Free JPEG to GIF Converter — no signup", heroSubline: "Upload any JPEG and get a GIF in seconds. No signup, no watermark, browser-based." },
  { slug: "free-jpg-to-gif-converter", canonical: "jpg-to-gif", seoTitle: "Free JPG to GIF Converter — No Watermark", seoDescription: "Free JPG to GIF converter online. No watermark, no signup, instant download.", keywords: ["free jpg to gif converter", "jpg to gif free"], h1Prefix: "Free", h1Highlight: "JPG to GIF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free JPG to GIF converter online. No watermark ever, no account required." },
  { slug: "jpg-gif-converter-online", canonical: "jpg-to-gif", seoTitle: "JPG to GIF Converter Online — Fast & Free", seoDescription: "Online JPG to GIF converter. Fast, free, no signup. Convert JPG photos to GIF format.", keywords: ["jpg gif converter online", "jpg to gif converter online"], h1Prefix: "The fast", h1Highlight: "JPG to GIF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to GIF", heroSubline: "Convert any JPG to GIF in seconds, right in your browser." },
  { slug: "change-jpg-to-gif", canonical: "jpg-to-gif", seoTitle: "Change JPG to GIF Online Free — No App", seoDescription: "Change JPG images to GIF format online. No app, no signup, instant conversion.", keywords: ["change jpg to gif", "how to convert jpg to gif"], h1Prefix: "Change", h1Highlight: "JPG to GIF", h1Suffix: "on any device.", eyebrow: "Change JPG to GIF — no app install needed", heroSubline: "Change any JPG to GIF online, free. Works on any device." },

  // ═══════════════════════ png-to-gif ═══════════════════════
  { slug: "convert-png-to-gif", canonical: "png-to-gif", seoTitle: "Convert PNG to GIF Online Free — No Signup", seoDescription: "Convert PNG to GIF online free. Create web-ready GIF images from PNG files. No signup, instant.", keywords: ["convert png to gif", "png to gif online"], h1Prefix: "Convert", h1Highlight: "PNG to GIF", h1Suffix: "online, free.", eyebrow: "PNG to GIF Converter — instant, browser-based", heroSubline: "Upload a PNG, get a web-ready GIF. No account, no watermark, no install needed." },
  { slug: "free-png-to-gif-converter", canonical: "png-to-gif", seoTitle: "Free PNG to GIF Converter — No Watermark", seoDescription: "Free PNG to GIF converter online. No watermark, no signup, instant download.", keywords: ["free png to gif converter", "png to gif free"], h1Prefix: "Free", h1Highlight: "PNG to GIF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to GIF converter online. No watermark ever, no account required." },
  { slug: "png-gif-converter-online", canonical: "png-to-gif", seoTitle: "PNG to GIF Converter Online — Fast & Free", seoDescription: "Online PNG to GIF converter. Fast, free, no signup. Convert PNG images to GIF format.", keywords: ["png gif converter online", "png to gif converter online"], h1Prefix: "The fast", h1Highlight: "PNG to GIF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to GIF", heroSubline: "Convert any PNG to GIF in seconds, right in your browser." },
  { slug: "png-to-gif-transparent", canonical: "png-to-gif", seoTitle: "PNG to GIF — Transparent Background", seoDescription: "Convert PNG to GIF online free with binary transparency support. No signup, instant download.", keywords: ["png to gif transparent", "transparent png to gif"], h1Prefix: "Convert PNG to GIF with", h1Highlight: "transparent background", h1Suffix: ".", eyebrow: "PNG to GIF — binary transparency supported", heroSubline: "Keep transparent areas when converting PNG to GIF. No signup, no watermark." },
  { slug: "change-png-to-gif", canonical: "png-to-gif", seoTitle: "Change PNG to GIF Online Free — No App", seoDescription: "Change PNG images to GIF format online. No app, no signup, instant. Web-ready output.", keywords: ["change png to gif", "how to convert png to gif"], h1Prefix: "Change", h1Highlight: "PNG to GIF", h1Suffix: "on any device.", eyebrow: "Change PNG to GIF — no app install needed", heroSubline: "Change any PNG to GIF online, free. Works on any device." },

  // ═══════════════════════ webp-to-gif ═══════════════════════
  { slug: "convert-webp-to-gif", canonical: "webp-to-gif", seoTitle: "Convert WebP to GIF Online Free — No Signup", seoDescription: "Convert WebP to GIF online free. Universal GIF compatibility. No signup, instant download.", keywords: ["convert webp to gif", "webp to gif online"], h1Prefix: "Convert", h1Highlight: "WebP to GIF", h1Suffix: "online, free.", eyebrow: "WebP to GIF Converter — universal compatibility", heroSubline: "Upload a WebP, get a universally compatible GIF. No account, no watermark, no install needed." },
  { slug: "free-webp-to-gif-converter", canonical: "webp-to-gif", seoTitle: "Free WebP to GIF Converter — No Watermark", seoDescription: "Free WebP to GIF converter online. No watermark, no signup, instant download. Browser-based.", keywords: ["free webp to gif converter", "webp to gif free"], h1Prefix: "Free", h1Highlight: "WebP to GIF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to GIF converter online. No watermark ever, no account required." },
  { slug: "webp-gif-converter-online", canonical: "webp-to-gif", seoTitle: "WebP to GIF Converter Online — Fast & Free", seoDescription: "Online WebP to GIF converter. Fast, free, no signup. Convert WebP images to GIF format.", keywords: ["webp gif converter online", "webp to gif converter online"], h1Prefix: "The fast", h1Highlight: "WebP to GIF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to GIF", heroSubline: "Convert any WebP to GIF in seconds, right in your browser." },
  { slug: "animated-webp-to-gif", canonical: "webp-to-gif", seoTitle: "Animated WebP to GIF Converter Free", seoDescription: "Convert animated WebP to GIF online free. No signup, instant download. Universal GIF support.", keywords: ["animated webp to gif", "convert animated webp to gif"], h1Prefix: "Convert", h1Highlight: "animated WebP to GIF", h1Suffix: ".", eyebrow: "Animated WebP to GIF — universal support", heroSubline: "Turn animated WebP files into universally compatible GIFs. No signup, no watermark." },
  { slug: "change-webp-to-gif", canonical: "webp-to-gif", seoTitle: "Change WebP to GIF Online Free — No App", seoDescription: "Change WebP images to GIF format online. No app, no signup, instant. Universal compatibility.", keywords: ["change webp to gif", "how to convert webp to gif"], h1Prefix: "Change", h1Highlight: "WebP to GIF", h1Suffix: "on any device.", eyebrow: "Change WebP to GIF — no app install needed", heroSubline: "Change any WebP to GIF online, free. Works on any device." },

  // ═══════════════════════ jpg-to-bmp ═══════════════════════
  { slug: "convert-jpg-to-bmp", canonical: "jpg-to-bmp", seoTitle: "Convert JPG to BMP Online Free — Uncompressed", seoDescription: "Convert JPG to BMP online free. Uncompressed bitmap for legacy software. No signup, instant.", keywords: ["convert jpg to bmp", "jpg to bmp online", "jpg to bitmap"], h1Prefix: "Convert", h1Highlight: "JPG to BMP", h1Suffix: "online, free.", eyebrow: "JPG to BMP Converter — uncompressed output", heroSubline: "Upload a JPG, get an uncompressed BMP. No account, no watermark, no install needed." },
  { slug: "jpeg-to-bmp", canonical: "jpg-to-bmp", seoTitle: "Free JPEG to BMP Converter — Uncompressed", seoDescription: "Convert JPEG to BMP online free. Uncompressed bitmap output for legacy apps. No signup, instant.", keywords: ["jpeg to bmp", "convert jpeg to bmp", "jpeg bmp converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to BMP", h1Suffix: "for free.", eyebrow: "Free JPEG to BMP Converter — no signup", heroSubline: "Upload any JPEG and get an uncompressed BMP. No signup, no watermark, browser-based." },
  { slug: "jpg-to-bitmap", canonical: "jpg-to-bmp", seoTitle: "JPG to Bitmap Converter Free Online", seoDescription: "Convert JPG to bitmap (BMP) online free. No signup, instant download. Uncompressed BMP output.", keywords: ["jpg to bitmap", "jpg to bmp bitmap", "convert jpg to bitmap"], h1Prefix: "Convert", h1Highlight: "JPG to bitmap", h1Suffix: "free.", eyebrow: "JPG to Bitmap — uncompressed BMP output", heroSubline: "Convert any JPG to an uncompressed bitmap (BMP) file. No signup, no watermark." },
  { slug: "jpg-bmp-converter-online", canonical: "jpg-to-bmp", seoTitle: "JPG to BMP Converter Online — Fast & Free", seoDescription: "Online JPG to BMP converter. Fast, free, no signup. Convert JPG to uncompressed BMP format.", keywords: ["jpg bmp converter online", "jpg to bmp converter online"], h1Prefix: "The fast", h1Highlight: "JPG to BMP converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to BMP", heroSubline: "Convert any JPG to uncompressed BMP in seconds, right in your browser." },
  { slug: "change-jpg-to-bmp", canonical: "jpg-to-bmp", seoTitle: "Change JPG to BMP Online Free — No App", seoDescription: "Change JPG images to BMP bitmap format online. No app, no signup, instant conversion.", keywords: ["change jpg to bmp", "how to convert jpg to bmp"], h1Prefix: "Change", h1Highlight: "JPG to BMP", h1Suffix: "on any device.", eyebrow: "Change JPG to BMP — no app install needed", heroSubline: "Change any JPG to BMP online, free. Works on any device." },

  // ═══════════════════════ png-to-bmp ═══════════════════════
  { slug: "convert-png-to-bmp", canonical: "png-to-bmp", seoTitle: "Convert PNG to BMP Online Free — Uncompressed", seoDescription: "Convert PNG to BMP online free. Uncompressed bitmap for legacy software. No signup, instant.", keywords: ["convert png to bmp", "png to bmp online", "png to bitmap"], h1Prefix: "Convert", h1Highlight: "PNG to BMP", h1Suffix: "online, free.", eyebrow: "PNG to BMP Converter — uncompressed output", heroSubline: "Upload a PNG, get an uncompressed BMP. No account, no watermark, no install needed." },
  { slug: "png-to-bitmap", canonical: "png-to-bmp", seoTitle: "PNG to Bitmap Converter Free Online", seoDescription: "Convert PNG to bitmap (BMP) online free. No signup, instant download. Uncompressed output.", keywords: ["png to bitmap", "png to bmp bitmap", "convert png to bitmap"], h1Prefix: "Convert", h1Highlight: "PNG to bitmap", h1Suffix: "free.", eyebrow: "PNG to Bitmap — uncompressed BMP output", heroSubline: "Convert any PNG to an uncompressed bitmap (BMP) file. No signup, no watermark." },
  { slug: "free-png-to-bmp-converter", canonical: "png-to-bmp", seoTitle: "Free PNG to BMP Converter — No Watermark", seoDescription: "Free PNG to BMP converter online. No watermark, no signup. Uncompressed bitmap output.", keywords: ["free png to bmp converter", "png to bmp free"], h1Prefix: "Free", h1Highlight: "PNG to BMP converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to BMP converter online. No watermark ever, no account required." },
  { slug: "png-bmp-converter-online", canonical: "png-to-bmp", seoTitle: "PNG to BMP Converter Online — Fast & Free", seoDescription: "Online PNG to BMP converter. Fast, free, no signup. Convert PNG to uncompressed bitmap.", keywords: ["png bmp converter online", "png to bmp converter online"], h1Prefix: "The fast", h1Highlight: "PNG to BMP converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to BMP", heroSubline: "Convert any PNG to uncompressed BMP in seconds, right in your browser." },
  { slug: "change-png-to-bmp", canonical: "png-to-bmp", seoTitle: "Change PNG to BMP Online Free — No App", seoDescription: "Change PNG images to BMP bitmap format online. No app, no signup, instant.", keywords: ["change png to bmp", "how to convert png to bmp"], h1Prefix: "Change", h1Highlight: "PNG to BMP", h1Suffix: "on any device.", eyebrow: "Change PNG to BMP — no app install needed", heroSubline: "Change any PNG to BMP online, free. Works on any device." },

  // ═══════════════════════ webp-to-bmp ═══════════════════════
  { slug: "convert-webp-to-bmp", canonical: "webp-to-bmp", seoTitle: "Convert WebP to BMP Online Free — Legacy", seoDescription: "Convert WebP to BMP online free. Uncompressed bitmap for legacy systems. No signup, instant.", keywords: ["convert webp to bmp", "webp to bmp online"], h1Prefix: "Convert", h1Highlight: "WebP to BMP", h1Suffix: "online, free.", eyebrow: "WebP to BMP Converter — legacy compatible", heroSubline: "Upload a WebP, get an uncompressed BMP. No account, no watermark, no install needed." },
  { slug: "free-webp-to-bmp-converter", canonical: "webp-to-bmp", seoTitle: "Free WebP to BMP Converter — No Watermark", seoDescription: "Free WebP to BMP converter online. No watermark, no signup. Uncompressed bitmap output.", keywords: ["free webp to bmp converter", "webp to bmp free"], h1Prefix: "Free", h1Highlight: "WebP to BMP converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to BMP converter online. No watermark ever, no account required." },
  { slug: "webp-bmp-converter-online", canonical: "webp-to-bmp", seoTitle: "WebP to BMP Converter Online — Fast & Free", seoDescription: "Online WebP to BMP converter. Fast, free, no signup. Convert WebP to uncompressed BMP.", keywords: ["webp bmp converter online", "webp to bmp converter online"], h1Prefix: "The fast", h1Highlight: "WebP to BMP converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to BMP", heroSubline: "Convert any WebP to uncompressed BMP in seconds, right in your browser." },
  { slug: "webp-to-bitmap", canonical: "webp-to-bmp", seoTitle: "WebP to Bitmap Converter Free Online", seoDescription: "Convert WebP to bitmap (BMP) online free. No signup, instant download. Uncompressed BMP output.", keywords: ["webp to bitmap", "webp to bmp bitmap"], h1Prefix: "Convert", h1Highlight: "WebP to bitmap", h1Suffix: "free.", eyebrow: "WebP to Bitmap — uncompressed BMP output", heroSubline: "Convert any WebP to an uncompressed bitmap (BMP) file. No signup, no watermark." },
  { slug: "change-webp-to-bmp", canonical: "webp-to-bmp", seoTitle: "Change WebP to BMP Online Free — No App", seoDescription: "Change WebP images to BMP bitmap format online. No app, no signup, instant.", keywords: ["change webp to bmp", "how to convert webp to bmp"], h1Prefix: "Change", h1Highlight: "WebP to BMP", h1Suffix: "on any device.", eyebrow: "Change WebP to BMP — no app install needed", heroSubline: "Change any WebP to BMP online, free. Works on any device." },

  // ═══════════════════════ jpg-to-tiff ═══════════════════════
  { slug: "convert-jpg-to-tiff", canonical: "jpg-to-tiff", seoTitle: "Convert JPG to TIFF Online Free — Print Ready", seoDescription: "Convert JPG to TIFF online free. Print-ready TIFF output for publishing. No signup, instant.", keywords: ["convert jpg to tiff", "jpg to tiff online", "jpg to tif"], h1Prefix: "Convert", h1Highlight: "JPG to TIFF", h1Suffix: "online, free.", eyebrow: "JPG to TIFF Converter — print-ready output", heroSubline: "Upload a JPG, get a print-ready TIFF. No account, no watermark, no install needed." },
  { slug: "jpeg-to-tiff", canonical: "jpg-to-tiff", seoTitle: "Free JPEG to TIFF Converter — Print Quality", seoDescription: "Convert JPEG to TIFF online free. Print-ready output for publishing. No signup, instant download.", keywords: ["jpeg to tiff", "convert jpeg to tiff", "jpeg tiff converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to TIFF", h1Suffix: "for free.", eyebrow: "Free JPEG to TIFF Converter — print quality", heroSubline: "Upload any JPEG and get a print-ready TIFF. No signup, no watermark, browser-based." },
  { slug: "jpg-to-tif", canonical: "jpg-to-tiff", seoTitle: "Free JPG to TIF Converter Online", seoDescription: "Convert JPG to TIF format online free. No signup, instant download. Print-ready output.", keywords: ["jpg to tif", "convert jpg to tif", "jpg to tif converter"], h1Prefix: "Convert", h1Highlight: "JPG to TIF", h1Suffix: "free.", eyebrow: "JPG to TIF Converter — .tif and .tiff output", heroSubline: "Convert any JPG to a print-ready TIF file. No signup, no watermark, browser-based." },
  { slug: "jpg-tiff-converter-online", canonical: "jpg-to-tiff", seoTitle: "JPG to TIFF Converter Online — Fast & Free", seoDescription: "Online JPG to TIFF converter. Fast, free, no signup. Professional print-ready TIFF output.", keywords: ["jpg tiff converter online", "jpg to tiff converter online"], h1Prefix: "The fast", h1Highlight: "JPG to TIFF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to TIFF", heroSubline: "Convert any JPG to print-ready TIFF in seconds, right in your browser." },
  { slug: "change-jpg-to-tiff", canonical: "jpg-to-tiff", seoTitle: "Change JPG to TIFF Online Free — No App", seoDescription: "Change JPG images to TIFF format online. No app, no signup, instant. Print-ready output.", keywords: ["change jpg to tiff", "how to convert jpg to tiff"], h1Prefix: "Change", h1Highlight: "JPG to TIFF", h1Suffix: "on any device.", eyebrow: "Change JPG to TIFF — no app install needed", heroSubline: "Change any JPG to print-ready TIFF online, free. Works on any device." },

  // ═══════════════════════ png-to-tiff ═══════════════════════
  { slug: "convert-png-to-tiff", canonical: "png-to-tiff", seoTitle: "Convert PNG to TIFF Online Free — Print Ready", seoDescription: "Convert PNG to TIFF online free. Lossless print-ready output. No signup, instant download.", keywords: ["convert png to tiff", "png to tiff online", "png to tif"], h1Prefix: "Convert", h1Highlight: "PNG to TIFF", h1Suffix: "online, free.", eyebrow: "PNG to TIFF Converter — lossless print output", heroSubline: "Upload a PNG, get a print-ready TIFF. No account, no watermark, no install needed." },
  { slug: "png-to-tif", canonical: "png-to-tiff", seoTitle: "Free PNG to TIF Converter Online", seoDescription: "Convert PNG to TIF format online free. Lossless output, no signup, instant download.", keywords: ["png to tif", "convert png to tif", "png to tif converter"], h1Prefix: "Convert", h1Highlight: "PNG to TIF", h1Suffix: "free.", eyebrow: "PNG to TIF Converter — lossless print output", heroSubline: "Convert any PNG to a print-ready TIF file. No signup, no watermark, browser-based." },
  { slug: "free-png-to-tiff-converter", canonical: "png-to-tiff", seoTitle: "Free PNG to TIFF Converter — No Watermark", seoDescription: "Free PNG to TIFF converter online. Lossless compression, no watermark, no signup.", keywords: ["free png to tiff converter", "png to tiff free"], h1Prefix: "Free", h1Highlight: "PNG to TIFF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to TIFF converter online. No watermark ever, no account required." },
  { slug: "png-tiff-converter-online", canonical: "png-to-tiff", seoTitle: "PNG to TIFF Converter Online — Fast & Free", seoDescription: "Online PNG to TIFF converter. Fast, free, no signup. Lossless TIFF output for print.", keywords: ["png tiff converter online", "png to tiff converter online"], h1Prefix: "The fast", h1Highlight: "PNG to TIFF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to TIFF", heroSubline: "Convert any PNG to lossless TIFF in seconds, right in your browser." },
  { slug: "change-png-to-tiff", canonical: "png-to-tiff", seoTitle: "Change PNG to TIFF Online Free — No App", seoDescription: "Change PNG images to TIFF format online. No app, no signup, instant. Lossless print output.", keywords: ["change png to tiff", "how to convert png to tiff"], h1Prefix: "Change", h1Highlight: "PNG to TIFF", h1Suffix: "on any device.", eyebrow: "Change PNG to TIFF — no app install needed", heroSubline: "Change any PNG to print-ready TIFF online, free. Works on any device." },

  // ═══════════════════════ webp-to-tiff ═══════════════════════
  { slug: "convert-webp-to-tiff", canonical: "webp-to-tiff", seoTitle: "Convert WebP to TIFF Online Free — Print Ready", seoDescription: "Convert WebP to TIFF online free. Print-ready output for professional use. No signup, instant.", keywords: ["convert webp to tiff", "webp to tiff online"], h1Prefix: "Convert", h1Highlight: "WebP to TIFF", h1Suffix: "online, free.", eyebrow: "WebP to TIFF Converter — print-ready output", heroSubline: "Upload a WebP, get a print-ready TIFF. No account, no watermark, no install needed." },
  { slug: "free-webp-to-tiff-converter", canonical: "webp-to-tiff", seoTitle: "Free WebP to TIFF Converter — No Watermark", seoDescription: "Free WebP to TIFF converter online. No watermark, no signup. Print-ready TIFF output.", keywords: ["free webp to tiff converter", "webp to tiff free"], h1Prefix: "Free", h1Highlight: "WebP to TIFF converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to TIFF converter online. No watermark ever, no account required." },
  { slug: "webp-tiff-converter-online", canonical: "webp-to-tiff", seoTitle: "WebP to TIFF Converter Online — Fast & Free", seoDescription: "Online WebP to TIFF converter. Fast, free, no signup. Convert WebP to print-ready TIFF.", keywords: ["webp tiff converter online", "webp to tiff converter online"], h1Prefix: "The fast", h1Highlight: "WebP to TIFF converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to TIFF", heroSubline: "Convert any WebP to print-ready TIFF in seconds, right in your browser." },
  { slug: "webp-to-tif", canonical: "webp-to-tiff", seoTitle: "Free WebP to TIF Converter Online", seoDescription: "Convert WebP to TIF format online free. No signup, instant download. Print-ready output.", keywords: ["webp to tif", "convert webp to tif", "webp to tif converter"], h1Prefix: "Convert", h1Highlight: "WebP to TIF", h1Suffix: "free.", eyebrow: "WebP to TIF Converter — print-ready output", heroSubline: "Convert any WebP to a print-ready TIF file. No signup, no watermark." },
  { slug: "change-webp-to-tiff", canonical: "webp-to-tiff", seoTitle: "Change WebP to TIFF Online Free — No App", seoDescription: "Change WebP images to TIFF format online. No app, no signup, instant. Print-ready.", keywords: ["change webp to tiff", "how to convert webp to tiff"], h1Prefix: "Change", h1Highlight: "WebP to TIFF", h1Suffix: "on any device.", eyebrow: "Change WebP to TIFF — no app install needed", heroSubline: "Change any WebP to print-ready TIFF online, free. Works on any device." },

  // ═══════════════════════ png-to-ico ═══════════════════════
  { slug: "convert-png-to-ico", canonical: "png-to-ico", seoTitle: "Convert PNG to ICO Online Free — Favicon", seoDescription: "Convert PNG to ICO online free. Create favicons and Windows icons. No signup, instant download.", keywords: ["convert png to ico", "png to ico online", "png to favicon"], h1Prefix: "Convert", h1Highlight: "PNG to ICO", h1Suffix: "online, free.", eyebrow: "PNG to ICO Converter — create favicons", heroSubline: "Upload a PNG logo, get a favicon ICO. No account, no watermark, no install needed." },
  { slug: "png-to-favicon", canonical: "png-to-ico", seoTitle: "PNG to Favicon Converter Free Online", seoDescription: "Convert PNG to favicon ICO online free. No signup, instant download. Create website favicons.", keywords: ["png to favicon", "convert png to favicon", "png favicon generator"], h1Prefix: "Create a", h1Highlight: "favicon from PNG", h1Suffix: "free.", eyebrow: "PNG to Favicon — ICO for any website", heroSubline: "Turn any PNG logo into a website favicon in seconds. No signup, no watermark." },
  { slug: "free-png-to-ico-converter", canonical: "png-to-ico", seoTitle: "Free PNG to ICO Converter — No Watermark", seoDescription: "Free PNG to ICO converter online. No watermark, no signup. Create favicons and icons instantly.", keywords: ["free png to ico converter", "png to ico free"], h1Prefix: "Free", h1Highlight: "PNG to ICO converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free PNG to ICO converter online. No watermark ever, no account required." },
  { slug: "png-ico-converter-online", canonical: "png-to-ico", seoTitle: "PNG to ICO Converter Online — Fast & Free", seoDescription: "Online PNG to ICO converter. Fast, free, no signup. Convert PNG logos to ICO icon files.", keywords: ["png ico converter online", "png to ico converter online"], h1Prefix: "The fast", h1Highlight: "PNG to ICO converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based PNG to ICO", heroSubline: "Convert any PNG to an ICO favicon in seconds, right in your browser." },
  { slug: "create-favicon-from-png", canonical: "png-to-ico", seoTitle: "Create Favicon from PNG Free Online", seoDescription: "Create a favicon ICO from any PNG image online free. No signup, no watermark, instant download.", keywords: ["create favicon from png", "favicon from png", "make favicon from png"], h1Prefix: "Create a", h1Highlight: "favicon from your PNG", h1Suffix: ".", eyebrow: "Favicon Creator — PNG to ICO, free", heroSubline: "Upload any PNG and create a pixel-perfect ICO favicon for your website. No signup required." },

  // ═══════════════════════ jpg-to-ico ═══════════════════════
  { slug: "convert-jpg-to-ico", canonical: "jpg-to-ico", seoTitle: "Convert JPG to ICO Online Free — Create Icons", seoDescription: "Convert JPG to ICO online free. Create favicons and Windows icons. No signup, instant download.", keywords: ["convert jpg to ico", "jpg to ico online", "jpg to favicon"], h1Prefix: "Convert", h1Highlight: "JPG to ICO", h1Suffix: "online, free.", eyebrow: "JPG to ICO Converter — create icons fast", heroSubline: "Upload a JPG, get an ICO icon or favicon. No account, no watermark, no install needed." },
  { slug: "jpeg-to-ico", canonical: "jpg-to-ico", seoTitle: "Free JPEG to ICO Converter — Create Favicons", seoDescription: "Convert JPEG to ICO online free. Create favicons and Windows icons. No signup, instant download.", keywords: ["jpeg to ico", "convert jpeg to ico", "jpeg ico converter online"], h1Prefix: "Convert", h1Highlight: "JPEG to ICO", h1Suffix: "for free.", eyebrow: "Free JPEG to ICO Converter — no signup", heroSubline: "Upload any JPEG and get an ICO favicon. No signup, no watermark, browser-based." },
  { slug: "jpg-to-favicon", canonical: "jpg-to-ico", seoTitle: "JPG to Favicon Converter Free Online", seoDescription: "Convert JPG to favicon ICO online free. No signup, instant download. Create website favicons.", keywords: ["jpg to favicon", "convert jpg to favicon", "jpg favicon generator"], h1Prefix: "Create a", h1Highlight: "favicon from JPG", h1Suffix: "free.", eyebrow: "JPG to Favicon — ICO for any website", heroSubline: "Turn any JPG into a website favicon in seconds. No signup, no watermark." },
  { slug: "jpg-ico-converter-online", canonical: "jpg-to-ico", seoTitle: "JPG to ICO Converter Online — Fast & Free", seoDescription: "Online JPG to ICO converter. Fast, free, no signup. Convert JPG images to ICO icon files.", keywords: ["jpg ico converter online", "jpg to ico converter online"], h1Prefix: "The fast", h1Highlight: "JPG to ICO converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based JPG to ICO", heroSubline: "Convert any JPG to an ICO favicon in seconds, right in your browser." },
  { slug: "change-jpg-to-ico", canonical: "jpg-to-ico", seoTitle: "Change JPG to ICO Online Free — No App", seoDescription: "Change JPG images to ICO icon format online. No app, no signup, instant conversion.", keywords: ["change jpg to ico", "how to convert jpg to ico"], h1Prefix: "Change", h1Highlight: "JPG to ICO", h1Suffix: "on any device.", eyebrow: "Change JPG to ICO — no app install needed", heroSubline: "Change any JPG to ICO online, free. Works on any device." },

  // ═══════════════════════ webp-to-ico ═══════════════════════
  { slug: "convert-webp-to-ico", canonical: "webp-to-ico", seoTitle: "Convert WebP to ICO Online Free — Favicons", seoDescription: "Convert WebP to ICO online free. Create favicons and Windows icons. No signup, instant download.", keywords: ["convert webp to ico", "webp to ico online", "webp to favicon"], h1Prefix: "Convert", h1Highlight: "WebP to ICO", h1Suffix: "online, free.", eyebrow: "WebP to ICO Converter — create favicons", heroSubline: "Upload a WebP, get an ICO favicon. No account, no watermark, no install needed." },
  { slug: "webp-to-favicon", canonical: "webp-to-ico", seoTitle: "WebP to Favicon Converter Free Online", seoDescription: "Convert WebP to favicon ICO online free. No signup, instant download. Create website favicons.", keywords: ["webp to favicon", "convert webp to favicon", "webp favicon generator"], h1Prefix: "Create a", h1Highlight: "favicon from WebP", h1Suffix: "free.", eyebrow: "WebP to Favicon — ICO for any website", heroSubline: "Turn any WebP image into a website favicon. No signup, no watermark." },
  { slug: "free-webp-to-ico-converter", canonical: "webp-to-ico", seoTitle: "Free WebP to ICO Converter — No Watermark", seoDescription: "Free WebP to ICO converter online. No watermark, no signup. Create favicons instantly.", keywords: ["free webp to ico converter", "webp to ico free"], h1Prefix: "Free", h1Highlight: "WebP to ICO converter", h1Suffix: "— no watermark.", eyebrow: "Zero watermark, zero signup — just convert", heroSubline: "The cleanest free WebP to ICO converter online. No watermark ever, no account required." },
  { slug: "webp-ico-converter-online", canonical: "webp-to-ico", seoTitle: "WebP to ICO Converter Online — Fast & Free", seoDescription: "Online WebP to ICO converter. Fast, free, no signup. Convert WebP images to ICO icon files.", keywords: ["webp ico converter online", "webp to ico converter online"], h1Prefix: "The fast", h1Highlight: "WebP to ICO converter", h1Suffix: "online.", eyebrow: "Fast, free, browser-based WebP to ICO", heroSubline: "Convert any WebP to an ICO favicon in seconds, right in your browser." },
  { slug: "change-webp-to-ico", canonical: "webp-to-ico", seoTitle: "Change WebP to ICO Online Free — No App", seoDescription: "Change WebP images to ICO icon format online. No app, no signup, instant conversion.", keywords: ["change webp to ico", "how to convert webp to ico"], h1Prefix: "Change", h1Highlight: "WebP to ICO", h1Suffix: "on any device.", eyebrow: "Change WebP to ICO — no app install needed", heroSubline: "Change any WebP to ICO online, free. Works on any device." },
];

const ALIAS_MAP = new Map(ALIASES.map((a) => [a.slug, a]));

/** All alias slugs (165 total — 5 per tool × 33 tools). */
export const IMAGE_CONVERTER_ALIAS_SLUGS: string[] = ALIASES.map((a) => a.slug);

/** Map export for callers that need direct access. */
export const IMAGE_CONVERTER_ALIAS_MAP: Map<string, ConverterAlias> = ALIAS_MAP;

/** Fetch an alias definition by slug (returns undefined if not an alias). */
export function getConverterAlias(slug: string): ConverterAlias | undefined {
  return ALIAS_MAP.get(slug);
}

/** True if the given slug is an image converter alias. */
export function isConverterAliasSlug(slug: string): boolean {
  return ALIAS_MAP.has(slug);
}
