/**
 * SEO alias slugs for the 9 image edit/compression tools.
 *
 * 5 aliases per tool = 45 total alias URLs. Same interface as
 * image-converter-aliases.ts — each alias renders the same underlying tool
 * but with a unique H1, eyebrow, subline, and metadata for a distinct
 * search-intent keyword cluster. Each self-canonicalizes so Google indexes
 * it independently.
 */

export interface EditAlias {
  /** URL slug — full path is /tools/<slug> */
  slug: string;
  /** Primary tool slug this alias belongs to (for tool resolution). */
  canonical: string;
  /** SEO title — ≤50 chars (template appends " | Trndinn"). */
  seoTitle: string;
  /** SEO meta description — 140-160 chars. */
  seoDescription: string;
  /** Keywords for meta + internal reporting. */
  keywords: string[];
  /** H1 text before the gradient-highlighted word. */
  h1Prefix: string;
  /** The gradient-highlighted word/phrase in the H1. */
  h1Highlight: string;
  /** H1 text after the gradient word. */
  h1Suffix: string;
  /** Small primary-tinted eyebrow badge above the hero. */
  eyebrow: string;
  /** Hero paragraph shown under the H1. */
  heroSubline: string;
}

const ALIASES: EditAlias[] = [
  // ═══════════════════════ compress-jpg ═══════════════════════
  {
    slug: "compress-jpeg-online",
    canonical: "compress-jpg",
    seoTitle: "Compress JPEG Online Free — Instant Download",
    seoDescription: "Compress JPEG images online free. Adjust quality slider, reduce file size up to 90%. No signup, browser-based — images never leave your device. Instant download.",
    keywords: ["compress jpeg online", "compress jpeg free", "jpeg compression online"],
    h1Prefix: "Compress",
    h1Highlight: "JPEG Online",
    h1Suffix: "for free.",
    eyebrow: "Free JPEG Compressor — no signup, no watermark",
    heroSubline: "Upload a JPEG, drag the quality slider, and download a smaller file in seconds. No account, no watermark, fully browser-based.",
  },
  {
    slug: "jpg-compressor",
    canonical: "compress-jpg",
    seoTitle: "Free JPG Compressor — Reduce File Size",
    seoDescription: "Free JPG compressor online. Reduce JPG file size by up to 90% with a quality slider. No signup, no watermark, browser-based. Instant download.",
    keywords: ["jpg compressor", "jpg compressor online free", "free jpg compressor"],
    h1Prefix: "Free",
    h1Highlight: "JPG Compressor",
    h1Suffix: "— reduce size instantly.",
    eyebrow: "Free JPG Compressor — zero signup, zero watermark",
    heroSubline: "Drag and drop your JPG, set quality, and get a smaller file — no server upload, no signup required.",
  },
  {
    slug: "reduce-jpg-file-size",
    canonical: "compress-jpg",
    seoTitle: "Reduce JPG File Size Online Free — Instant",
    seoDescription: "Reduce JPG file size online free. Cut image size by up to 90% without visible quality loss. No signup required, browser-based, instant download.",
    keywords: ["reduce jpg file size", "reduce jpg size online", "shrink jpg file size"],
    h1Prefix: "Reduce",
    h1Highlight: "JPG File Size",
    h1Suffix: "online, instantly.",
    eyebrow: "Reduce JPG size — no upload, no account",
    heroSubline: "Cut your JPG file size by up to 90% with a single slider. Everything runs in your browser — nothing is ever uploaded.",
  },
  {
    slug: "compress-jpeg-without-losing-quality",
    canonical: "compress-jpg",
    seoTitle: "Compress JPEG Without Losing Quality — Free",
    seoDescription: "Compress JPEG without losing quality online. Use 75-85% quality for 50% size reduction with no visible change. No signup, browser-based, instant download.",
    keywords: ["compress jpeg without losing quality", "compress jpg without quality loss", "high quality jpg compression"],
    h1Prefix: "Compress JPEG",
    h1Highlight: "without losing quality",
    h1Suffix: "— free online.",
    eyebrow: "Smart JPEG compression — quality preserved",
    heroSubline: "Our quality slider defaults to 80% — the sweet spot for 50%+ size reduction with no perceptible quality loss. All in your browser.",
  },
  {
    slug: "jpeg-optimizer-online",
    canonical: "compress-jpg",
    seoTitle: "Free JPEG Optimizer Online — Instant Download",
    seoDescription: "Optimize JPEG images online free. Reduce file size while preserving visual quality. No signup, no uploads, browser-based. Instant download.",
    keywords: ["jpeg optimizer online", "jpeg optimizer free", "optimize jpeg online"],
    h1Prefix: "Free",
    h1Highlight: "JPEG Optimizer",
    h1Suffix: "online.",
    eyebrow: "Free JPEG Optimizer — instant, browser-based",
    heroSubline: "Optimize your JPEG for web, email, or social media. Smaller files, same great image quality. Zero signup required.",
  },

  // ═══════════════════════ compress-png ═══════════════════════
  {
    slug: "png-compressor-online",
    canonical: "compress-png",
    seoTitle: "PNG Compressor Online Free — Reduce PNG Size",
    seoDescription: "Compress PNG images online free. Reduce PNG file size up to 80% while preserving transparency. No signup, browser-based, instant download.",
    keywords: ["png compressor online", "compress png online free", "png compression tool"],
    h1Prefix: "Free",
    h1Highlight: "PNG Compressor",
    h1Suffix: "online.",
    eyebrow: "Free PNG Compressor — transparency preserved",
    heroSubline: "Compress any PNG including those with transparent backgrounds. Reduce file size by up to 80% — runs entirely in your browser.",
  },
  {
    slug: "reduce-png-file-size",
    canonical: "compress-png",
    seoTitle: "Reduce PNG File Size Online Free — Instant",
    seoDescription: "Reduce PNG file size online free. Lossless and lossy compression options. Preserves transparency. No signup, browser-based, instant download.",
    keywords: ["reduce png file size", "reduce png size online", "shrink png file"],
    h1Prefix: "Reduce",
    h1Highlight: "PNG File Size",
    h1Suffix: "online, free.",
    eyebrow: "Shrink PNG size — transparency intact",
    heroSubline: "Reduce PNG file size without losing alpha channel transparency. Drag, compress, download — no upload needed.",
  },
  {
    slug: "optimize-png-online",
    canonical: "compress-png",
    seoTitle: "Optimize PNG Online Free — Smaller PNG Files",
    seoDescription: "Optimize PNG images online free. Reduce file size for faster websites without visible quality loss. No signup, browser-based, instant download.",
    keywords: ["optimize png online", "optimize png free", "png optimizer online"],
    h1Prefix: "Optimize",
    h1Highlight: "PNG Online",
    h1Suffix: "for faster loading.",
    eyebrow: "Free PNG Optimizer — browser-based, instant",
    heroSubline: "Smaller PNG files load faster on websites and in emails. Optimize in seconds — no upload, no account required.",
  },
  {
    slug: "compress-png-without-losing-quality",
    canonical: "compress-png",
    seoTitle: "Compress PNG Without Losing Quality — Free",
    seoDescription: "Compress PNG without losing quality online free. Reduce file size 40-80% while keeping visual fidelity. No signup, browser-based, instant download.",
    keywords: ["compress png without losing quality", "lossless png compression online", "compress transparent png"],
    h1Prefix: "Compress PNG",
    h1Highlight: "without losing quality",
    h1Suffix: "— free online.",
    eyebrow: "Lossless-first PNG compression",
    heroSubline: "Compress PNG files without visible quality loss. Choose lossless for pixel-perfect output or lossy for maximum size reduction.",
  },
  {
    slug: "png-file-size-reducer",
    canonical: "compress-png",
    seoTitle: "PNG File Size Reducer — Free Online Tool",
    seoDescription: "Free PNG file size reducer online. Reduce PNG images up to 80% smaller. Preserves transparency. No signup, no uploads, browser-based. Instant download.",
    keywords: ["png file size reducer", "make png smaller online", "png size reducer free"],
    h1Prefix: "Free",
    h1Highlight: "PNG File Size Reducer",
    h1Suffix: "— instant results.",
    eyebrow: "PNG size reducer — zero signup, zero watermark",
    heroSubline: "Make your PNG files up to 80% smaller in seconds. Works entirely in your browser — no file ever leaves your device.",
  },

  // ═══════════════════════ compress-webp ═══════════════════════
  {
    slug: "webp-compressor-online",
    canonical: "compress-webp",
    seoTitle: "WebP Compressor Online Free — Reduce WebP Size",
    seoDescription: "Compress WebP images online free. Reduce WebP file size with quality control. No signup, browser-based — images never leave your device. Instant download.",
    keywords: ["webp compressor online", "compress webp online free", "webp compression tool"],
    h1Prefix: "Free",
    h1Highlight: "WebP Compressor",
    h1Suffix: "online.",
    eyebrow: "Free WebP Compressor — browser-based, instant",
    heroSubline: "Compress WebP images further for even faster web performance. Quality slider, no uploads, no signup required.",
  },
  {
    slug: "reduce-webp-file-size",
    canonical: "compress-webp",
    seoTitle: "Reduce WebP File Size Online Free — Instant",
    seoDescription: "Reduce WebP file size online free. Get 20-50% smaller WebP files with a quality slider. No signup, browser-based, instant download.",
    keywords: ["reduce webp file size", "reduce webp size online", "shrink webp file"],
    h1Prefix: "Reduce",
    h1Highlight: "WebP File Size",
    h1Suffix: "online, free.",
    eyebrow: "WebP size reducer — no upload needed",
    heroSubline: "Reduce your WebP file size by 20-50% with a single quality adjustment. Everything stays in your browser.",
  },
  {
    slug: "optimize-webp-online",
    canonical: "compress-webp",
    seoTitle: "Optimize WebP Online Free — Smaller Files",
    seoDescription: "Optimize WebP images online free. Reduce file size for faster web page load times. No signup, no uploads, browser-based. Instant download.",
    keywords: ["optimize webp online", "webp optimizer free", "optimize webp for web"],
    h1Prefix: "Optimize",
    h1Highlight: "WebP Online",
    h1Suffix: "for the web.",
    eyebrow: "Free WebP Optimizer — instant results",
    heroSubline: "Get even faster page load times by optimizing your WebP images. No server upload — runs entirely in your browser.",
  },
  {
    slug: "compress-webp-without-losing-quality",
    canonical: "compress-webp",
    seoTitle: "Compress WebP Without Losing Quality — Free",
    seoDescription: "Compress WebP without losing quality online free. Reduce file size 20-50% with minimal visual impact. No signup, browser-based, instant download.",
    keywords: ["compress webp without losing quality", "webp compression no quality loss", "high quality webp compression"],
    h1Prefix: "Compress WebP",
    h1Highlight: "without losing quality",
    h1Suffix: "— free online.",
    eyebrow: "Smart WebP compression — quality first",
    heroSubline: "Our quality slider defaults to 80% — smaller WebP files with no perceptible loss in sharpness or color. No signup, no upload.",
  },
  {
    slug: "webp-file-size-reducer",
    canonical: "compress-webp",
    seoTitle: "WebP File Size Reducer — Free Online Tool",
    seoDescription: "Free WebP file size reducer online. Make WebP files 20-50% smaller for faster loading. No signup, browser-based, instant download.",
    keywords: ["webp file size reducer", "make webp smaller online", "webp size reducer"],
    h1Prefix: "Free",
    h1Highlight: "WebP File Size Reducer",
    h1Suffix: "— faster web pages.",
    eyebrow: "WebP size reducer — browser-based, zero signup",
    heroSubline: "Make WebP files smaller for faster websites. Drag your file, adjust quality, download — nothing is ever uploaded.",
  },

  // ═══════════════════════ compress-gif ═══════════════════════
  {
    slug: "gif-compressor-online",
    canonical: "compress-gif",
    seoTitle: "GIF Compressor Online Free — Reduce GIF Size",
    seoDescription: "Compress GIF images online free. Reduce animated or static GIF file size without ruining quality. No signup, browser-based, instant download.",
    keywords: ["gif compressor online", "compress gif online free", "gif compression tool"],
    h1Prefix: "Free",
    h1Highlight: "GIF Compressor",
    h1Suffix: "online.",
    eyebrow: "Free GIF Compressor — animation intact",
    heroSubline: "Reduce GIF file size without ruining animation frames. Works on animated and static GIFs — fully in your browser.",
  },
  {
    slug: "reduce-gif-file-size",
    canonical: "compress-gif",
    seoTitle: "Reduce GIF File Size Online Free — Instant",
    seoDescription: "Reduce GIF file size online free. Cut animated GIF size by 30-70%. No signup, no uploads, browser-based. Instant download.",
    keywords: ["reduce gif file size", "reduce gif size online", "shrink gif file"],
    h1Prefix: "Reduce",
    h1Highlight: "GIF File Size",
    h1Suffix: "online, free.",
    eyebrow: "GIF size reducer — no upload, no account",
    heroSubline: "Shrink your GIF file size by up to 70%. Works on animated GIFs without breaking frames. Entirely browser-based.",
  },
  {
    slug: "optimize-gif-online",
    canonical: "compress-gif",
    seoTitle: "Optimize GIF Online Free — Smaller Animated GIFs",
    seoDescription: "Optimize GIF files online free. Reduce animated GIF file size for faster loading on web and social. No signup, browser-based, instant download.",
    keywords: ["optimize gif online", "gif optimizer free", "optimize animated gif"],
    h1Prefix: "Optimize",
    h1Highlight: "GIF Online",
    h1Suffix: "for faster loading.",
    eyebrow: "Free GIF Optimizer — instant, browser-based",
    heroSubline: "Make your animated GIFs load faster on websites and social media. Reduce size without breaking animation.",
  },
  {
    slug: "compress-gif-without-losing-quality",
    canonical: "compress-gif",
    seoTitle: "Compress GIF Without Losing Quality — Free",
    seoDescription: "Compress GIF without losing quality online free. Reduce GIF file size 30-70% while keeping animation smooth. No signup, browser-based, instant download.",
    keywords: ["compress gif without losing quality", "gif compression no quality loss", "small gif no quality loss"],
    h1Prefix: "Compress GIF",
    h1Highlight: "without losing quality",
    h1Suffix: "— free online.",
    eyebrow: "GIF compression — smooth animation preserved",
    heroSubline: "Reduce GIF file size without choppy frames or color banding. All compression happens in your browser.",
  },
  {
    slug: "gif-file-size-reducer",
    canonical: "compress-gif",
    seoTitle: "GIF File Size Reducer — Free Online Tool",
    seoDescription: "Free GIF file size reducer online. Reduce animated GIF size by 30-70% with no watermark. No signup, browser-based, instant download.",
    keywords: ["gif file size reducer", "make gif smaller online", "gif size reducer free"],
    h1Prefix: "Free",
    h1Highlight: "GIF File Size Reducer",
    h1Suffix: "— instant results.",
    eyebrow: "GIF size reducer — zero signup, zero watermark",
    heroSubline: "Make your GIFs up to 70% smaller in seconds. Animation stays smooth — everything runs in your browser.",
  },

  // ═══════════════════════ image-resizer ═══════════════════════
  {
    slug: "resize-image-online",
    canonical: "image-resizer",
    seoTitle: "Resize Image Online Free — Instant Download",
    seoDescription: "Resize any image online free. Enter custom dimensions or use platform presets for LinkedIn, Instagram, Twitter, YouTube, Facebook. No signup, browser-based.",
    keywords: ["resize image online", "resize image online free", "image resize tool online"],
    h1Prefix: "Resize",
    h1Highlight: "Image Online",
    h1Suffix: "for free.",
    eyebrow: "Free Image Resizer — no signup, no watermark",
    heroSubline: "Upload any image, enter dimensions or pick a platform preset, and download your resized image instantly. No account required.",
  },
  {
    slug: "photo-resizer",
    canonical: "image-resizer",
    seoTitle: "Free Photo Resizer Online — No Signup Needed",
    seoDescription: "Free photo resizer online. Resize photos to exact pixel dimensions or platform presets. No signup, no uploads, browser-based. Instant download.",
    keywords: ["photo resizer", "photo resizer online free", "free photo resizer"],
    h1Prefix: "Free",
    h1Highlight: "Photo Resizer",
    h1Suffix: "online.",
    eyebrow: "Free Photo Resizer — browser-based, instant",
    heroSubline: "Resize photos for web, print, or social media in seconds. Dimensions stay pixel-perfect, quality stays high.",
  },
  {
    slug: "resize-image-without-losing-quality",
    canonical: "image-resizer",
    seoTitle: "Resize Image Without Losing Quality — Free",
    seoDescription: "Resize images without losing quality online free. High-quality canvas interpolation preserves sharpness. No signup, browser-based, instant download.",
    keywords: ["resize image without losing quality", "resize photo without quality loss", "high quality image resize online"],
    h1Prefix: "Resize Image",
    h1Highlight: "without losing quality",
    h1Suffix: "— free online.",
    eyebrow: "Quality-first image resizing — browser-based",
    heroSubline: "Our resizer uses high-quality interpolation for sharp, crisp output at any size. No uploads, no watermark, no signup.",
  },
  {
    slug: "linkedin-image-size",
    canonical: "image-resizer",
    seoTitle: "LinkedIn Image Size Tool — Resize Free",
    seoDescription: "Resize images to exact LinkedIn dimensions free. Profile 400×400, banner 1584×396, post 1200×628. One-click presets, browser-based, instant download.",
    keywords: ["linkedin image size", "linkedin image dimensions", "resize image for linkedin free"],
    h1Prefix: "LinkedIn",
    h1Highlight: "Image Size Tool",
    h1Suffix: "— resize free.",
    eyebrow: "LinkedIn image dimensions — one-click presets",
    heroSubline: "One-click presets for every LinkedIn image: Profile (400×400), Banner (1584×396), Post (1200×628). No signup needed.",
  },
  {
    slug: "instagram-image-size",
    canonical: "image-resizer",
    seoTitle: "Instagram Image Size Tool — Resize Free",
    seoDescription: "Resize images to exact Instagram dimensions free. Square 1080×1080, Story 1080×1920, Portrait 1080×1350. One-click presets, browser-based, instant download.",
    keywords: ["instagram image size", "instagram image dimensions 2026", "resize image for instagram free"],
    h1Prefix: "Instagram",
    h1Highlight: "Image Size Tool",
    h1Suffix: "— resize free.",
    eyebrow: "Instagram image dimensions — one-click presets",
    heroSubline: "One-click presets for every Instagram format: Square (1080×1080), Story (1080×1920), Portrait (1080×1350). No account needed.",
  },

  // ═══════════════════════ image-cropper ═══════════════════════
  {
    slug: "crop-image-online",
    canonical: "image-cropper",
    seoTitle: "Crop Image Online Free — Instant Download",
    seoDescription: "Crop any image online free. Set exact pixel crop area with X/Y offset and dimension controls. No signup, browser-based, instant download.",
    keywords: ["crop image online", "crop image online free", "image crop tool online"],
    h1Prefix: "Crop",
    h1Highlight: "Image Online",
    h1Suffix: "for free.",
    eyebrow: "Free Image Cropper — no signup, no watermark",
    heroSubline: "Upload your image, set the crop area with precise pixel controls, and download the result instantly. No account needed.",
  },
  {
    slug: "crop-photo-free",
    canonical: "image-cropper",
    seoTitle: "Free Photo Cropper Online — No Signup",
    seoDescription: "Free photo cropper online. Crop photos to exact dimensions with pixel-precise controls. No signup, browser-based, instant download. Works on all devices.",
    keywords: ["crop photo free", "crop photo online free", "free photo cropper online"],
    h1Prefix: "Free",
    h1Highlight: "Photo Cropper",
    h1Suffix: "online.",
    eyebrow: "Free Photo Cropper — browser-based, instant",
    heroSubline: "Crop photos with pixel-precision controls for web, social media, or print. Nothing is uploaded — it all runs in your browser.",
  },
  {
    slug: "crop-image-to-circle",
    canonical: "image-cropper",
    seoTitle: "Crop Image to Circle Online Free — Instant",
    seoDescription: "Crop image to circle online free. Set equal width and height for circular crop. No signup, browser-based, instant download. Works on PNG with transparency.",
    keywords: ["crop image to circle", "crop image circle online free", "circular image crop tool"],
    h1Prefix: "Crop Image",
    h1Highlight: "to Circle",
    h1Suffix: "online, free.",
    eyebrow: "Circular image crop — transparency preserved",
    heroSubline: "Set equal width and height for a perfect circle crop. Works great for profile photos — transparent background preserved on PNG.",
  },
  {
    slug: "free-image-cropper",
    canonical: "image-cropper",
    seoTitle: "Free Image Cropper — No Signup Required",
    seoDescription: "Free image cropper online. Crop images to any size with precise pixel controls. No signup, no watermark, browser-based. Instant download.",
    keywords: ["free image cropper", "free image cropper online", "image cropper no signup"],
    h1Prefix: "Free",
    h1Highlight: "Image Cropper",
    h1Suffix: "— no signup.",
    eyebrow: "Free Image Cropper — zero signup, zero watermark",
    heroSubline: "The cleanest free image cropper online. No account, no watermark, no size limits — just precise pixel-perfect cropping.",
  },
  {
    slug: "crop-and-resize-image",
    canonical: "image-cropper",
    seoTitle: "Crop and Resize Image Online Free — Instant",
    seoDescription: "Crop and resize images online free. Combine crop and resize in one tool. No signup, browser-based, instant download. Works on JPG, PNG, and WebP.",
    keywords: ["crop and resize image", "crop and resize image online free", "resize and crop photo online"],
    h1Prefix: "Crop and Resize",
    h1Highlight: "Image Online",
    h1Suffix: "free.",
    eyebrow: "Crop + resize in one — browser-based",
    heroSubline: "Crop your image to the perfect composition then resize for your target platform — no upload, no signup required.",
  },

  // ═══════════════════════ image-rotator ═══════════════════════
  {
    slug: "rotate-image-online",
    canonical: "image-rotator",
    seoTitle: "Rotate Image Online Free — Instant Download",
    seoDescription: "Rotate any image online free. Rotate 90°, 180°, 270°, or flip horizontally and vertically. No signup, browser-based, instant download.",
    keywords: ["rotate image online", "rotate image online free", "image rotation tool online"],
    h1Prefix: "Rotate",
    h1Highlight: "Image Online",
    h1Suffix: "for free.",
    eyebrow: "Free Image Rotator — no signup, no watermark",
    heroSubline: "Rotate or flip any image in one click. 90°, 180°, 270°, flip horizontal, flip vertical — all in your browser, instantly.",
  },
  {
    slug: "flip-image-online",
    canonical: "image-rotator",
    seoTitle: "Flip Image Online Free — Mirror Any Photo",
    seoDescription: "Flip images online free. Mirror images horizontally or vertically with one click. No signup, browser-based, instant download. Works on all image formats.",
    keywords: ["flip image online", "flip image online free", "mirror image online free"],
    h1Prefix: "Flip",
    h1Highlight: "Image Online",
    h1Suffix: "for free.",
    eyebrow: "Free Image Flipper — browser-based, instant",
    heroSubline: "Mirror any image horizontally or vertically with a single click. No upload, no account — runs entirely in your browser.",
  },
  {
    slug: "rotate-photo-90-degrees",
    canonical: "image-rotator",
    seoTitle: "Rotate Photo 90 Degrees Free — Online Tool",
    seoDescription: "Rotate photos 90 degrees online free. One-click 90°, 180°, or 270° rotation. No signup, browser-based, instant download. Works on JPG, PNG, and WebP.",
    keywords: ["rotate photo 90 degrees", "rotate image 90 degrees online free", "rotate picture 90 degrees"],
    h1Prefix: "Rotate Photo",
    h1Highlight: "90 Degrees",
    h1Suffix: "— free online.",
    eyebrow: "Quick 90° rotation — one click, no upload",
    heroSubline: "Rotate sideways photos upright in one click. 90°, 180°, or 270° — all browser-based with no quality loss on PNG.",
  },
  {
    slug: "mirror-image-online",
    canonical: "image-rotator",
    seoTitle: "Mirror Image Online Free — Flip Any Photo",
    seoDescription: "Mirror images online free. Flip photos horizontally or vertically for mirror effect. No signup, browser-based, instant download.",
    keywords: ["mirror image online", "mirror image online free", "mirror photo online"],
    h1Prefix: "Mirror",
    h1Highlight: "Image Online",
    h1Suffix: "for free.",
    eyebrow: "Free Image Mirror Tool — instant, browser-based",
    heroSubline: "Create a mirror image of any photo with one click. Flip horizontal or vertical — no upload, no account needed.",
  },
  {
    slug: "rotate-image-without-losing-quality",
    canonical: "image-rotator",
    seoTitle: "Rotate Image Free — No Quality Loss",
    seoDescription: "Rotate images online free without losing quality. Lossless rotation for PNG, minimal re-encoding for JPG. No signup, browser-based, instant download.",
    keywords: ["rotate image without losing quality", "lossless image rotation online", "rotate photo no quality loss"],
    h1Prefix: "Rotate Image Free",
    h1Highlight: "— No Quality Loss",
    h1Suffix: ".",
    eyebrow: "Quality-preserving rotation — browser-based",
    heroSubline: "PNG rotation is fully lossless. JPG rotation re-encodes once at original quality. No upload, no watermark, no signup.",
  },

  // ═══════════════════════ watermark-image ═══════════════════════
  {
    slug: "add-watermark-to-photo",
    canonical: "watermark-image",
    seoTitle: "Add Watermark to Photo Free — Online Tool",
    seoDescription: "Add a watermark to any photo online free. Text or logo watermark, 9 positions, opacity control. No signup, browser-based, instant download.",
    keywords: ["add watermark to photo", "add watermark to photo free", "photo watermark tool"],
    h1Prefix: "Add",
    h1Highlight: "Watermark to Photo",
    h1Suffix: "free.",
    eyebrow: "Free Photo Watermark Tool — no signup needed",
    heroSubline: "Protect your photos with a text or logo watermark. Choose position, opacity, and font — entirely in your browser.",
  },
  {
    slug: "watermark-photo-online",
    canonical: "watermark-image",
    seoTitle: "Watermark Photo Online Free — Instant",
    seoDescription: "Watermark photos online free. Add text or image watermark with full position and opacity control. No signup, browser-based, instant download.",
    keywords: ["watermark photo online", "watermark photo online free", "online photo watermark tool"],
    h1Prefix: "Watermark",
    h1Highlight: "Photo Online",
    h1Suffix: "for free.",
    eyebrow: "Free Photo Watermark — browser-based, instant",
    heroSubline: "Add your watermark online in seconds. Text or logo, any position, any opacity. No upload to any server.",
  },
  {
    slug: "add-text-to-image-free",
    canonical: "watermark-image",
    seoTitle: "Add Text to Image Free Online — Instant",
    seoDescription: "Add text to any image online free. Choose font size, color, position, and opacity. No signup, browser-based, instant download. Works on all formats.",
    keywords: ["add text to image free", "add text to image online free", "text overlay on image online"],
    h1Prefix: "Add",
    h1Highlight: "Text to Image",
    h1Suffix: "free online.",
    eyebrow: "Free text overlay tool — browser-based, instant",
    heroSubline: "Add custom text to any image — choose font size, color, position, and opacity. No account, no watermark on your output.",
  },
  {
    slug: "photo-watermark-maker",
    canonical: "watermark-image",
    seoTitle: "Free Photo Watermark Maker — Online Tool",
    seoDescription: "Free photo watermark maker online. Create text or logo watermarks with position and opacity control. No signup, browser-based, instant download.",
    keywords: ["photo watermark maker", "free watermark maker online", "create photo watermark"],
    h1Prefix: "Free",
    h1Highlight: "Photo Watermark Maker",
    h1Suffix: "online.",
    eyebrow: "Free Watermark Maker — zero signup, zero cost",
    heroSubline: "Create professional watermarks for your photos with full control over text, position, and opacity. Everything runs in your browser.",
  },
  {
    slug: "protect-image-with-watermark",
    canonical: "watermark-image",
    seoTitle: "Protect Image with Watermark Free Online",
    seoDescription: "Protect images with a watermark online free. Add text or logo watermark to prevent unauthorized use. No signup, browser-based, instant download.",
    keywords: ["protect image with watermark", "watermark images to protect copyright", "copyright watermark photo"],
    h1Prefix: "Protect Image",
    h1Highlight: "with Watermark",
    h1Suffix: "— free online.",
    eyebrow: "Copyright protection — add watermarks instantly",
    heroSubline: "Stop unauthorized use of your images. Add a visible watermark in seconds — no account required, no file leaves your device.",
  },

  // ═══════════════════════ image-workbench ═══════════════════════
  {
    slug: "online-image-editor",
    canonical: "image-workbench",
    seoTitle: "Free Online Image Editor — No Download",
    seoDescription: "Free online image editor. Resize, crop, rotate, compress, and convert images in one multi-step pipeline. No signup, no download, browser-based.",
    keywords: ["online image editor", "free online image editor", "image editor online no download"],
    h1Prefix: "Free",
    h1Highlight: "Online Image Editor",
    h1Suffix: "— no download.",
    eyebrow: "Free Image Editor — browser-based, no signup",
    heroSubline: "Edit images online with a full pipeline editor. Chain multiple operations and apply them in one pass — no app install, no account.",
  },
  {
    slug: "edit-image-online-free",
    canonical: "image-workbench",
    seoTitle: "Edit Image Online Free — No Signup Needed",
    seoDescription: "Edit images online free with no signup. Resize, crop, rotate, compress, convert in a multi-op pipeline. Browser-based, instant download.",
    keywords: ["edit image online free", "edit photo online free no signup", "image editing online free"],
    h1Prefix: "Edit",
    h1Highlight: "Image Online Free",
    h1Suffix: "— no signup.",
    eyebrow: "Free image editing — zero signup, zero cost",
    heroSubline: "Upload an image, build your edit pipeline, and download the result — free with no account required.",
  },
  {
    slug: "image-editing-tool-free",
    canonical: "image-workbench",
    seoTitle: "Free Image Editing Tool Online — Multi-Op",
    seoDescription: "Free image editing tool online. Chain resize, crop, rotate, compress, and convert operations in one pipeline. No signup, browser-based, instant download.",
    keywords: ["image editing tool free", "free image editing tool online", "multi-step image editor online"],
    h1Prefix: "Free",
    h1Highlight: "Image Editing Tool",
    h1Suffix: "online.",
    eyebrow: "Multi-op image editing — browser-based",
    heroSubline: "The only free browser image editor that chains multiple operations in one pipeline. No watermark, no signup, no limits.",
  },
  {
    slug: "photo-editor-no-download",
    canonical: "image-workbench",
    seoTitle: "Free Photo Editor — No Download Required",
    seoDescription: "Free photo editor online with no download required. Resize, crop, rotate, compress, convert in one pass. No signup, browser-based, instant download.",
    keywords: ["photo editor no download", "free photo editor no download no signup", "photo editor online no install"],
    h1Prefix: "Free Photo Editor",
    h1Highlight: "— No Download",
    h1Suffix: "required.",
    eyebrow: "Photo editor — no install, no signup, free",
    heroSubline: "A full-featured photo editor that runs entirely in your browser. No download, no app install, no account needed.",
  },
  {
    slug: "advanced-image-editor-online",
    canonical: "image-workbench",
    seoTitle: "Advanced Image Editor Online Free",
    seoDescription: "Advanced image editor online free. Pipeline-based editing: chain resize, crop, rotate, compress, and convert operations. No signup, browser-based.",
    keywords: ["advanced image editor online", "advanced photo editing online free", "professional image editor browser"],
    h1Prefix: "Advanced",
    h1Highlight: "Image Editor Online",
    h1Suffix: "free.",
    eyebrow: "Pipeline-based image editing — free, browser-based",
    heroSubline: "Build multi-step edit pipelines with precise control over each operation. The most advanced free browser image editor available.",
  },
];

// ---------------------------------------------------------------------------
// Lookup map
// ---------------------------------------------------------------------------

const ALIAS_MAP = new Map<string, EditAlias>(ALIASES.map((a) => [a.slug, a]));

export const IMAGE_EDIT_ALIAS_SLUGS: string[] = ALIASES.map((a) => a.slug);

export function getEditAlias(slug: string): EditAlias | undefined {
  return ALIAS_MAP.get(slug);
}

export function isEditAliasSlug(slug: string): boolean {
  return ALIAS_MAP.has(slug);
}
