/** Remove internal model attribution footer from generated captions. */
const MODEL_ATTRIBUTION_RE = /\n*\n[—-]\s*Generated by[\s\S]*$/i;

export function stripModelAttribution(text: string | null | undefined): string {
  if (!text) return '';
  return text.replace(MODEL_ATTRIBUTION_RE, '').trimEnd();
}
