"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Loader2,
  Plus,
  Trash2,
  Zap,
  Server,
  KeyRound,
  Clock,
  ChevronUp,
  ChevronDown,
  Type,
  Image as ImageIcon,
  Video,
  Search,
  CheckCircle2,
  Sparkles,
  Globe,
  Eye,
  EyeOff,
  ExternalLink,
} from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/apiClient";
import { getErrorMessage } from "@/lib/error-handler";
import type {
  AiModelsState,
  AiModelCategory,
  AiCatalogModel,
  AiModelTestResult,
  AiModelEntry,
  WebResearchConfigResponse,
  WebResearchTestResult,
} from "@/types/aiModels";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const PROVIDER_STYLE: Record<string, string> = {
  bedrock: "bg-orange-500/15 text-orange-600 dark:text-orange-400",
  openai: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  gemini: "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  vertex: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
  anthropic: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
};

const CATEGORY_META: Record<
  AiModelCategory,
  {
    label: string;
    icon: typeof Type;
    blurb: string;
    examples: string[];
    placeholder: string;
  }
> = {
  text: {
    label: "Text",
    icon: Type,
    blurb:
      "Used everywhere text is generated or formatted — Agent generation, custom topics, carousels, AI formatting, post refinement, Brand Kit Smart Import, SEO & careers copy.",
    examples: [
      "bedrock/moonshotai.kimi-k2.5",
      "openai/gpt-4o",
      "gemini/gemini-2.5-flash",
      "vertex/gemini-2.5-pro",
      "anthropic/claude-3-5-sonnet-20241022-v2:0",
    ],
    placeholder: "bedrock/moonshotai.kimi-k2.5",
  },
  text_formatter: {
    label: "AI Formatter (cheap)",
    icon: Type,
    blurb:
      "A cheap, fast model that cleans the user's raw prompt — fixes grammar & punctuation and structures it WITHOUT dropping any keywords or changing meaning. The cleaned prompt is what feeds both the post generation and the Tavily web search (so search gets the full structured prompt, not stripped keywords). Pick a very cheap model here. If empty, prompts are sent as-is (no formatting).",
    examples: [
      "openai/gpt-4o-mini",
      "openai/gpt-4.1-mini",
      "gemini/gemini-2.5-flash",
      "bedrock/anthropic.claude-3-5-haiku-20241022-v1:0",
    ],
    placeholder: "openai/gpt-4o-mini",
  },
  vision: {
    label: "Vision / Analysis",
    icon: Eye,
    blurb:
      "Used to ANALYZE images you upload — Brand Kit logo & reference images are read by this model to extract colors, style, and logo description that guide image generation. Add vision-capable text models (Claude, GPT, Gemini). If empty, falls back to the active Text model.",
    examples: [
      "bedrock/global.anthropic.claude-sonnet-4-6",
      "openai/gpt-5.2",
      "gemini/gemini-2.5-pro",
      "vertex/gemini-2.5-pro",
    ],
    placeholder: "bedrock/global.anthropic.claude-sonnet-4-6",
  },
  image: {
    label: "Image",
    icon: ImageIcon,
    blurb:
      "Used for image & carousel slide generation. Add image-capable models only (uses the gateway /images/generations endpoint).",
    examples: [
      "vertex/imagen-4.0-generate-001",
      "openai/gpt-image-1",
      "openai/dall-e-3",
      "gemini/imagen-4.0-generate-001",
    ],
    placeholder: "vertex/imagen-4.0-generate-001",
  },
  image_context: {
    label: "Image (Context-Aware)",
    icon: Zap,
    blurb:
      "GPT models that generate images via the Responses API with the image_generation tool. The model reads the full post caption + brand context and generates a semantically relevant image. Preferred over plain Image models when post content is available. Add text-capable GPT models that support image generation (gpt-5.5, gpt-4o, gpt-4.1, etc.).",
    examples: [
      "openai/gpt-4o",
      "openai/gpt-4.1",
      "openai/gpt-4.1-mini",
      "openai/gpt-5.5",
    ],
    placeholder: "openai/gpt-4o",
  },
  image_enhance: {
    label: "Image Enhance",
    icon: Sparkles,
    blurb:
      "Upscale, enhance, or refine images generated by other models. These models accept an existing image as input and output an improved version. Used when a user requests image improvement.",
    examples: [
      "bedrock/stability.stable-creative-upscale-v1:0",
      "bedrock/stability.sd3-5-large-v1:0",
    ],
    placeholder: "bedrock/stability.stable-creative-upscale-v1:0",
  },
  video: {
    label: "Video",
    icon: Video,
    blurb:
      "Video generation isn't wired into the product yet. Models you add here are saved for future use; testing just confirms the gateway is reachable.",
    examples: ["vertex/veo-3.0-generate-001", "openai/sora-2"],
    placeholder: "vertex/veo-3.0-generate-001",
  },
};

const CATEGORIES: AiModelCategory[] = ["text", "text_formatter", "vision", "image", "image_context", "image_enhance", "video"];

export function AdminAiModels() {
  const [state, setState] = useState<AiModelsState | null>(null);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<AiModelCategory>("text");
  const [busyId, setBusyId] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  const [newLabel, setNewLabel] = useState("");
  const [newModel, setNewModel] = useState("");
  const [testingId, setTestingId] = useState<string | null>(null);
  const [results, setResults] = useState<Record<string, AiModelTestResult>>({});

  // Web Research (Tavily)
  const [wrConfig, setWrConfig] = useState<WebResearchConfigResponse | null>(null);
  const [wrLoading, setWrLoading] = useState(false);
  const [wrKeyInput, setWrKeyInput] = useState("");
  const [wrShowKey, setWrShowKey] = useState(false);
  const [wrSaving, setWrSaving] = useState(false);
  const [wrTesting, setWrTesting] = useState(false);
  const [wrTestResult, setWrTestResult] = useState<WebResearchTestResult | null>(null);

  // Catalog browser
  const [catalogOpen, setCatalogOpen] = useState(false);
  const [catalog, setCatalog] = useState<AiCatalogModel[] | null>(null);
  const [catalogLoading, setCatalogLoading] = useState(false);
  const [catalogError, setCatalogError] = useState<string | null>(null);
  const [catalogSearch, setCatalogSearch] = useState("");

  // Vision try-it tester
  const [visionImage, setVisionImage] = useState<string | null>(null);
  const [visionImageName, setVisionImageName] = useState<string>("");
  const [visionModel, setVisionModel] = useState<string>("");
  const [visionPrompt, setVisionPrompt] = useState<string>("");
  const [visionRunning, setVisionRunning] = useState(false);
  const [visionResult, setVisionResult] = useState<{
    ok: boolean;
    model?: string;
    analysis?: string;
    latencyMs: number;
    message?: string;
  } | null>(null);

  const load = async () => {
    try {
      setState(await api.admin.aiModelsList());
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setLoading(false);
    }
  };

  const loadWrConfig = async () => {
    setWrLoading(true);
    try {
      setWrConfig(await api.admin.webResearchGet());
    } catch {
      // non-critical
    } finally {
      setWrLoading(false);
    }
  };

  useEffect(() => {
    void load();
    void loadWrConfig();
  }, []);

  const modelsByCategory = useMemo(() => {
    const map: Record<AiModelCategory, AiModelEntry[]> = {
      text: [],
      text_formatter: [],
      vision: [],
      image: [],
      image_context: [],
      image_enhance: [],
      video: [],
    };
    if (!state) return map;
    for (const cat of CATEGORIES) {
      const inCat = state.models.filter((m) => m.category === cat);
      const activeId = state.active[cat];
      // Mirror the backend chain: active first, then the rest in stored order.
      inCat.sort((a, b) => {
        if (a.id === activeId) return -1;
        if (b.id === activeId) return 1;
        return 0;
      });
      map[cat] = inCat;
    }
    return map;
  }, [state]);

  const handleAdd = async (category: AiModelCategory, model: string, label?: string) => {
    const trimmed = model.trim();
    if (!trimmed) {
      toast.error("Enter a model string like " + CATEGORY_META[category].placeholder);
      return;
    }
    setAdding(true);
    try {
      const next = await api.admin.aiModelsAdd({
        model: trimmed,
        label: label?.trim() || undefined,
        category,
      });
      setState(next);
      setNewLabel("");
      setNewModel("");
      toast.success("Model added to " + CATEGORY_META[category].label + ".");
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setAdding(false);
    }
  };

  const handleSetActive = async (category: AiModelCategory, id: string) => {
    setBusyId(id);
    try {
      setState(await api.admin.aiModelsSetActive(category, id));
      toast.success("Primary model updated.");
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setBusyId(null);
    }
  };

  const handleToggleEnabled = async (id: string, enabled: boolean) => {
    setBusyId(id);
    try {
      setState(await api.admin.aiModelsSetEnabled(id, enabled));
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setBusyId(null);
    }
  };

  const handleRemove = async (id: string) => {
    setBusyId(id);
    try {
      setState(await api.admin.aiModelsRemove(id));
      toast.success("Model removed.");
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setBusyId(null);
    }
  };

  const handleReorder = async (
    category: AiModelCategory,
    list: AiModelEntry[],
    index: number,
    dir: -1 | 1,
  ) => {
    const target = index + dir;
    if (target < 0 || target >= list.length) return;
    const reordered = [...list];
    const [moved] = reordered.splice(index, 1);
    reordered.splice(target, 0, moved);
    const orderedIds = reordered.map((m) => m.id);
    setBusyId(moved.id);
    try {
      setState(await api.admin.aiModelsReorder(category, orderedIds));
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setBusyId(null);
    }
  };

  const handleTest = async (id: string, model: string, category: AiModelCategory) => {
    setTestingId(id);
    try {
      const res = await api.admin.aiModelsTest(model, category);
      setResults((prev) => ({ ...prev, [id]: res }));
      if (res.ok) toast.success(`OK · ${res.latencyMs}ms`);
      else toast.error(res.message);
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setTestingId(null);
    }
  };

  const openCatalog = async () => {
    setCatalogOpen(true);
    if (catalog || catalogLoading) return;
    setCatalogLoading(true);
    setCatalogError(null);
    try {
      const res = await api.admin.aiModelsCatalog();
      if (res.ok) setCatalog(res.models);
      else setCatalogError(res.message || "Could not load gateway models.");
    } catch (error) {
      setCatalogError(getErrorMessage(error));
    } finally {
      setCatalogLoading(false);
    }
  };

  const handleVisionImagePick = (file: File | null) => {
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      toast.error("Please choose an image file.");
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      toast.error("Image too large (max 10MB).");
      return;
    }
    const reader = new FileReader();
    reader.onload = () => {
      setVisionImage(typeof reader.result === "string" ? reader.result : null);
      setVisionImageName(file.name);
      setVisionResult(null);
    };
    reader.onerror = () => toast.error("Could not read the image file.");
    reader.readAsDataURL(file);
  };

  const handleRunVisionAnalyze = async () => {
    if (!visionImage) {
      toast.error("Upload an image first.");
      return;
    }
    const model =
      visionModel ||
      modelsByCategory.vision[0]?.model ||
      modelsByCategory.text[0]?.model ||
      "";
    if (!model) {
      toast.error("No vision/text model configured to analyze with.");
      return;
    }
    setVisionRunning(true);
    setVisionResult(null);
    try {
      const res = await api.admin.aiModelsVisionAnalyze(
        model,
        visionImage,
        visionPrompt.trim() || undefined,
      );
      setVisionResult(res);
      if (res.ok) toast.success(`Analyzed with ${res.model}`);
      else toast.error(res.message || "Analysis failed.");
    } catch (error) {
      setVisionResult({
        ok: false,
        latencyMs: 0,
        message: getErrorMessage(error),
      });
      toast.error(getErrorMessage(error));
    } finally {
      setVisionRunning(false);
    }
  };

  if (loading) {
    return (
      <div className="flex h-40 items-center justify-center">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const gw = state?.gateway;
  const existingModelStrings = new Set(
    (state?.models || []).map((m) => `${m.category}:${m.model.toLowerCase()}`),
  );

  return (
    <div className="space-y-5">
      {/* Gateway status */}
      <Card>
        <CardContent className="flex flex-wrap items-center gap-x-6 gap-y-2 p-4 text-xs">
          <span className="flex items-center gap-1.5">
            <Server className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-muted-foreground">Gateway:</span>
            <code className="font-mono">{gw?.baseUrl || "—"}</code>
          </span>
          <span className="flex items-center gap-1.5">
            <KeyRound className="h-3.5 w-3.5 text-muted-foreground" />
            {gw?.hasApiKey ? (
              <span className="text-emerald-600 dark:text-emerald-400">API key set</span>
            ) : (
              <span className="text-destructive">No API key</span>
            )}
          </span>
          <span className="flex items-center gap-1.5">
            <Clock className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-muted-foreground">Timeout:</span>
            {gw?.timeoutMs ?? "—"}ms
          </span>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="ml-auto h-8"
            onClick={openCatalog}
          >
            <Search className="h-4 w-4" />
            <span className="ml-1.5">Browse gateway models</span>
          </Button>
        </CardContent>
      </Card>

      <p className="text-xs text-muted-foreground">
        One env-driven Bifrost virtual key routes Bedrock, OpenAI, Gemini &amp;
        Vertex by the <code className="font-mono">provider/model</code> prefix.
        Within each category the list is a <strong>fallback chain</strong>: the
        primary model is tried first, then the others top-to-bottom — so a single
        model outage never fails a request.
      </p>

      {/* Web Research (Tavily) */}
      <Card>
        <CardContent className="space-y-4 p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Globe className="h-4 w-4 text-blue-500" />
              <span className="text-sm font-medium">Web Research</span>
              <Badge variant="outline" className="text-[10px]">Tavily</Badge>
            </div>
            {wrConfig && (
              <div className="flex items-center gap-2">
                <Switch
                  checked={wrConfig.enabled}
                  onCheckedChange={async (enabled) => {
                    setWrSaving(true);
                    try {
                      setWrConfig(await api.admin.webResearchUpdate({ enabled }));
                      toast.success(enabled ? "Web research enabled" : "Web research disabled");
                    } catch (error) {
                      toast.error(getErrorMessage(error));
                    } finally {
                      setWrSaving(false);
                    }
                  }}
                  disabled={wrSaving}
                />
                <span className="text-xs text-muted-foreground">
                  {wrConfig.enabled ? "Enabled" : "Disabled"}
                </span>
              </div>
            )}
          </div>

          <p className="text-xs text-muted-foreground">
            Live web search via{" "}
            <a
              href="https://tavily.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-500 underline underline-offset-2 hover:text-blue-400"
            >
              Tavily <ExternalLink className="inline-block h-3 w-3" />
            </a>{" "}
            — grounds AI-generated posts in real-time data, recent events, and
            trending topics. Results are injected into the LLM system prompt for
            authentic, data-driven content.
          </p>

          {wrLoading ? (
            <div className="flex h-12 items-center justify-center">
              <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
            </div>
          ) : wrConfig ? (
            <div className="space-y-3">
              {/* API Key */}
              <div className="space-y-1.5">
                <Label className="text-xs">Tavily API Key</Label>
                <div className="flex gap-2">
                  <div className="relative flex-1">
                    <Input
                      type={wrShowKey ? "text" : "password"}
                      placeholder={wrConfig.hasApiKey ? wrConfig.keyPreview : "tvly-..."}
                      value={wrKeyInput}
                      onChange={(e) => setWrKeyInput(e.target.value)}
                      className="pr-8 font-mono text-xs"
                    />
                    <button
                      type="button"
                      className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                      onClick={() => setWrShowKey(!wrShowKey)}
                    >
                      {wrShowKey ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
                    </button>
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    disabled={!wrKeyInput.trim() || wrSaving}
                    onClick={async () => {
                      setWrSaving(true);
                      try {
                        setWrConfig(
                          await api.admin.webResearchUpdate({
                            tavilyApiKey: wrKeyInput.trim(),
                          }),
                        );
                        setWrKeyInput("");
                        toast.success("Tavily API key updated");
                      } catch (error) {
                        toast.error(getErrorMessage(error));
                      } finally {
                        setWrSaving(false);
                      }
                    }}
                  >
                    {wrSaving ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : "Save Key"}
                  </Button>
                </div>
                {wrConfig.hasApiKey && (
                  <p className="text-[11px] text-emerald-600 dark:text-emerald-400">
                    Key set: {wrConfig.keyPreview}
                  </p>
                )}
              </div>

              {/* Config options */}
              <div className="grid grid-cols-3 gap-3">
                <div className="space-y-1">
                  <Label className="text-[11px] text-muted-foreground">Max Results</Label>
                  <Select
                    value={String(wrConfig.maxResults)}
                    onValueChange={async (v) => {
                      setWrSaving(true);
                      try {
                        setWrConfig(
                          await api.admin.webResearchUpdate({ maxResults: Number(v) }),
                        );
                      } catch (error) {
                        toast.error(getErrorMessage(error));
                      } finally {
                        setWrSaving(false);
                      }
                    }}
                  >
                    <SelectTrigger className="h-8 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {[3, 5, 8, 10].map((n) => (
                        <SelectItem key={n} value={String(n)}>
                          {n} sources
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label className="text-[11px] text-muted-foreground">Search Depth</Label>
                  <Select
                    value={wrConfig.searchDepth}
                    onValueChange={async (v) => {
                      setWrSaving(true);
                      try {
                        setWrConfig(
                          await api.admin.webResearchUpdate({
                            searchDepth: v as "basic" | "advanced",
                          }),
                        );
                      } catch (error) {
                        toast.error(getErrorMessage(error));
                      } finally {
                        setWrSaving(false);
                      }
                    }}
                  >
                    <SelectTrigger className="h-8 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="basic">Basic (1 credit)</SelectItem>
                      <SelectItem value="advanced">Advanced (2 credits)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label className="text-[11px] text-muted-foreground">Time Range</Label>
                  <Select
                    value={wrConfig.timeRange || "all"}
                    onValueChange={async (v) => {
                      setWrSaving(true);
                      try {
                        setWrConfig(
                          await api.admin.webResearchUpdate({
                            timeRange: v === "all" ? "" : (v as "day" | "week" | "month" | "year"),
                          }),
                        );
                      } catch (error) {
                        toast.error(getErrorMessage(error));
                      } finally {
                        setWrSaving(false);
                      }
                    }}
                  >
                    <SelectTrigger className="h-8 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All time</SelectItem>
                      <SelectItem value="day">Past day</SelectItem>
                      <SelectItem value="week">Past week</SelectItem>
                      <SelectItem value="month">Past month</SelectItem>
                      <SelectItem value="year">Past year</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Test */}
              <div className="flex items-center gap-2 border-t pt-3">
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  className="gap-1.5"
                  disabled={wrTesting || !wrConfig.hasApiKey}
                  onClick={async () => {
                    setWrTesting(true);
                    setWrTestResult(null);
                    try {
                      const res = await api.admin.webResearchTest();
                      setWrTestResult(res);
                      if (res.ok) toast.success(`Search OK · ${res.responseTimeMs}ms · ${res.sourceCount} sources`);
                      else toast.error(res.message || "Test failed");
                    } catch (error) {
                      toast.error(getErrorMessage(error));
                    } finally {
                      setWrTesting(false);
                    }
                  }}
                >
                  {wrTesting ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Zap className="h-3.5 w-3.5" />
                  )}
                  Test Search
                </Button>
                {!wrConfig.hasApiKey && (
                  <span className="text-xs text-destructive">Set an API key first</span>
                )}
              </div>

              {/* Test results */}
              {wrTestResult && wrTestResult.ok && (
                <div className="rounded-md border border-emerald-500/30 bg-emerald-500/5 p-3 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-medium text-emerald-600 dark:text-emerald-400">
                      Search successful
                    </span>
                    <span className="text-[10px] text-muted-foreground">
                      {wrTestResult.responseTimeMs}ms · {wrTestResult.sourceCount} sources
                    </span>
                  </div>
                  {wrTestResult.answer && (
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      {wrTestResult.answer.slice(0, 300)}
                      {(wrTestResult.answer?.length ?? 0) > 300 ? "…" : ""}
                    </p>
                  )}
                  {wrTestResult.sources?.map((src, i) => (
                    <div key={i} className="text-[11px]">
                      <a
                        href={src.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-500 hover:underline"
                      >
                        {src.title}
                      </a>
                      <p className="text-muted-foreground mt-0.5 line-clamp-2">{src.snippet}</p>
                    </div>
                  ))}
                </div>
              )}
              {wrTestResult && !wrTestResult.ok && (
                <div className="rounded-md border border-destructive/30 bg-destructive/5 p-3">
                  <p className="text-xs text-destructive">{wrTestResult.message}</p>
                </div>
              )}
            </div>
          ) : null}
        </CardContent>
      </Card>

      <Tabs value={tab} onValueChange={(v) => setTab(v as AiModelCategory)}>
        <TabsList>
          {CATEGORIES.map((cat) => {
            const Icon = CATEGORY_META[cat].icon;
            const count = modelsByCategory[cat].length;
            return (
              <TabsTrigger key={cat} value={cat} className="gap-1.5">
                <Icon className="h-4 w-4" />
                {CATEGORY_META[cat].label}
                {count > 0 && (
                  <span className="ml-1 rounded-full bg-muted px-1.5 text-[10px]">
                    {count}
                  </span>
                )}
              </TabsTrigger>
            );
          })}
        </TabsList>

        {CATEGORIES.map((cat) => (
          <TabsContent key={cat} value={cat} className="space-y-4 pt-4">
            <p className="text-xs text-muted-foreground">{CATEGORY_META[cat].blurb}</p>

            {cat === "vision" && (
              <Card className="border-dashed">
                <CardContent className="space-y-3 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium">
                    <Eye className="h-4 w-4 text-primary" />
                    Try it — upload an image and see what the model analyzes
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Upload any image (logo, screenshot, reference). The selected
                    vision model will describe its colors, style, logo, and
                    composition — exactly how the Brand Kit analysis works.
                  </p>

                  <div className="grid gap-3 sm:grid-cols-2">
                    <div className="space-y-2">
                      <Label className="text-xs">Image (max 10MB)</Label>
                      <label className="flex h-32 cursor-pointer flex-col items-center justify-center rounded-md border border-dashed border-border bg-muted/30 text-center transition hover:bg-muted/50">
                        {visionImage ? (
                          // eslint-disable-next-line @next/next/no-img-element
                          <img
                            src={visionImage}
                            alt="preview"
                            className="max-h-28 max-w-full rounded object-contain"
                          />
                        ) : (
                          <span className="flex flex-col items-center gap-1 px-2 text-xs text-muted-foreground">
                            <Plus className="h-5 w-5" />
                            Click to upload an image
                          </span>
                        )}
                        <input
                          type="file"
                          accept="image/*"
                          className="hidden"
                          onChange={(e) =>
                            handleVisionImagePick(e.target.files?.[0] ?? null)
                          }
                        />
                      </label>
                      {visionImageName && (
                        <p className="truncate text-[11px] text-muted-foreground">
                          {visionImageName}
                        </p>
                      )}
                    </div>

                    <div className="space-y-2">
                      <Label className="text-xs">Model</Label>
                      <select
                        className="h-9 w-full rounded-md border border-border bg-background px-2 text-xs"
                        value={visionModel}
                        onChange={(e) => setVisionModel(e.target.value)}
                      >
                        <option value="">
                          {modelsByCategory.vision[0]?.model
                            ? `Active vision: ${modelsByCategory.vision[0].model}`
                            : modelsByCategory.text[0]?.model
                              ? `Fallback text: ${modelsByCategory.text[0].model}`
                              : "No model configured"}
                        </option>
                        {modelsByCategory.vision.map((m) => (
                          <option key={`v-${m.id}`} value={m.model}>
                            vision: {m.model}
                          </option>
                        ))}
                        {modelsByCategory.text.map((m) => (
                          <option key={`t-${m.id}`} value={m.model}>
                            text: {m.model}
                          </option>
                        ))}
                      </select>
                      <Label className="text-xs">Prompt (optional)</Label>
                      <Input
                        value={visionPrompt}
                        onChange={(e) => setVisionPrompt(e.target.value)}
                        placeholder="Leave empty for the default brand-analysis prompt"
                        className="h-9 text-xs"
                      />
                      <Button
                        type="button"
                        size="sm"
                        className="w-full"
                        disabled={!visionImage || visionRunning}
                        onClick={handleRunVisionAnalyze}
                      >
                        {visionRunning ? (
                          <>
                            <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                            Analyzing…
                          </>
                        ) : (
                          <>
                            <Eye className="mr-1.5 h-3.5 w-3.5" />
                            Analyze image
                          </>
                        )}
                      </Button>
                    </div>
                  </div>

                  {visionResult && (
                    <div
                      className={
                        "rounded-md border p-3 text-xs " +
                        (visionResult.ok
                          ? "border-emerald-500/40 bg-emerald-500/5"
                          : "border-destructive/40 bg-destructive/5")
                      }
                    >
                      <div className="mb-1 flex items-center justify-between font-medium">
                        <span className="flex items-center gap-1.5">
                          {visionResult.ok ? (
                            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                          ) : (
                            <Trash2 className="h-3.5 w-3.5 text-destructive" />
                          )}
                          {visionResult.ok
                            ? `Analyzed by ${visionResult.model}`
                            : "Analysis failed"}
                        </span>
                        <span className="text-muted-foreground">
                          {visionResult.latencyMs}ms
                        </span>
                      </div>
                      <p className="whitespace-pre-wrap leading-relaxed text-foreground/90">
                        {visionResult.ok
                          ? visionResult.analysis
                          : visionResult.message}
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}

            {/* Model list */}
            <div className="space-y-2">
              {modelsByCategory[cat].length === 0 && (
                <Card>
                  <CardContent className="p-6 text-center text-sm text-muted-foreground">
                    No {CATEGORY_META[cat].label.toLowerCase()} models yet. Add
                    one below or browse gateway models.
                  </CardContent>
                </Card>
              )}
              {modelsByCategory[cat].map((m, idx) => {
                const isPrimary = m.id === state?.active[cat] && m.enabled;
                const result = results[m.id];
                const list = modelsByCategory[cat];
                return (
                  <Card
                    key={m.id}
                    className={
                      isPrimary
                        ? "border-primary/50 bg-primary/[0.03]"
                        : !m.enabled
                          ? "opacity-60"
                          : ""
                    }
                  >
                    <CardContent className="flex flex-wrap items-center gap-3 p-3">
                      {/* Priority reorder */}
                      <div className="flex flex-col">
                        <button
                          type="button"
                          aria-label="Move up"
                          disabled={idx === 0 || busyId === m.id}
                          onClick={() => handleReorder(cat, list, idx, -1)}
                          className="text-muted-foreground hover:text-foreground disabled:opacity-30"
                        >
                          <ChevronUp className="h-3.5 w-3.5" />
                        </button>
                        <button
                          type="button"
                          aria-label="Move down"
                          disabled={idx === list.length - 1 || busyId === m.id}
                          onClick={() => handleReorder(cat, list, idx, 1)}
                          className="text-muted-foreground hover:text-foreground disabled:opacity-30"
                        >
                          <ChevronDown className="h-3.5 w-3.5" />
                        </button>
                      </div>

                      {/* Primary radio */}
                      <button
                        type="button"
                        onClick={() => !isPrimary && handleSetActive(cat, m.id)}
                        disabled={busyId === m.id || isPrimary}
                        aria-label={isPrimary ? "Primary model" : "Set as primary"}
                        title={isPrimary ? "Primary model" : "Set as primary"}
                        className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-border disabled:cursor-default"
                      >
                        {isPrimary ? (
                          <span className="h-2.5 w-2.5 rounded-full bg-primary" />
                        ) : busyId === m.id ? (
                          <Loader2 className="h-3 w-3 animate-spin" />
                        ) : null}
                      </button>

                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="truncate text-sm font-medium">
                            {m.label}
                          </span>
                          <Badge
                            variant="secondary"
                            className={PROVIDER_STYLE[m.provider] || ""}
                          >
                            {m.provider}
                          </Badge>
                          {isPrimary ? (
                            <Badge className="gap-1">
                              <CheckCircle2 className="h-3 w-3" />
                              Primary
                            </Badge>
                          ) : (
                            <Badge variant="outline" className="text-[10px]">
                              Fallback #{idx}
                            </Badge>
                          )}
                        </div>
                        <code className="block truncate font-mono text-[11px] text-muted-foreground">
                          {m.model}
                        </code>
                        {result && (
                          <span
                            className={`text-[11px] ${result.ok ? "text-emerald-600 dark:text-emerald-400" : "text-destructive"}`}
                          >
                            {result.ok ? `✓ ${result.latencyMs}ms` : result.message}
                          </span>
                        )}
                      </div>

                      <div className="flex items-center gap-1.5">
                        <span className="text-[10px] text-muted-foreground">
                          {m.enabled ? "On" : "Off"}
                        </span>
                        <Switch
                          checked={m.enabled}
                          disabled={busyId === m.id}
                          onCheckedChange={(v) => handleToggleEnabled(m.id, v)}
                          aria-label="Enable model"
                        />
                      </div>

                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        className="h-8"
                        disabled={testingId === m.id}
                        onClick={() => handleTest(m.id, m.model, cat)}
                      >
                        {testingId === m.id ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          <Zap className="h-4 w-4" />
                        )}
                        <span className="ml-1.5">Test</span>
                      </Button>
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-muted-foreground hover:text-destructive"
                        aria-label="Remove model"
                        disabled={busyId === m.id}
                        onClick={() => handleRemove(m.id)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </CardContent>
                  </Card>
                );
              })}
            </div>

            {/* Add model */}
            <Card>
              <CardContent className="space-y-3 p-4">
                <h2 className="text-sm font-semibold">
                  Add a {CATEGORY_META[cat].label.toLowerCase()} model
                </h2>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-[1fr_1.4fr_auto]">
                  <div className="space-y-1.5">
                    <Label className="text-xs">Label (optional)</Label>
                    <Input
                      value={tab === cat ? newLabel : ""}
                      onChange={(e) => setNewLabel(e.target.value)}
                      placeholder="e.g. Primary"
                      className="h-9"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs">Model string (provider/model)</Label>
                    <Input
                      value={tab === cat ? newModel : ""}
                      onChange={(e) => setNewModel(e.target.value)}
                      placeholder={CATEGORY_META[cat].placeholder}
                      className="h-9 font-mono text-xs"
                      onKeyDown={(e) => {
                        if (e.key === "Enter") {
                          e.preventDefault();
                          void handleAdd(cat, newModel, newLabel);
                        }
                      }}
                    />
                  </div>
                  <div className="flex items-end">
                    <Button
                      type="button"
                      className="h-9 w-full sm:w-auto"
                      disabled={adding}
                      onClick={() => handleAdd(cat, newModel, newLabel)}
                    >
                      {adding ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Plus className="h-4 w-4" />
                      )}
                      <span className="ml-1.5">Add</span>
                    </Button>
                  </div>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  <span className="text-[11px] text-muted-foreground">Examples:</span>
                  {CATEGORY_META[cat].examples.map((ex) => (
                    <button
                      key={ex}
                      type="button"
                      onClick={() => {
                        setTab(cat);
                        setNewModel(ex);
                      }}
                      className="rounded-full border border-border px-2 py-0.5 font-mono text-[10px] text-muted-foreground transition-colors hover:border-primary hover:text-primary"
                    >
                      {ex}
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        ))}
      </Tabs>

      {/* Catalog browser dialog */}
      <Dialog open={catalogOpen} onOpenChange={setCatalogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Gateway models · {CATEGORY_META[tab].label}</DialogTitle>
          </DialogHeader>
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="relative flex-1">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  value={catalogSearch}
                  onChange={(e) => setCatalogSearch(e.target.value)}
                  placeholder="Filter models…"
                  className="h-9 pl-8"
                />
              </div>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="h-9"
                disabled={catalogLoading}
                onClick={async () => {
                  setCatalogLoading(true);
                  try {
                    const res = await api.admin.aiModelsCatalog(true);
                    if (res.ok) setCatalog(res.models);
                    else setCatalogError(res.message || "Could not load.");
                  } catch (error) {
                    setCatalogError(getErrorMessage(error));
                  } finally {
                    setCatalogLoading(false);
                  }
                }}
              >
                Refresh
              </Button>
            </div>
            <p className="text-[11px] text-muted-foreground">
              {tab === "text_formatter" ? (
                <>
                  Showing <strong>text-capable models</strong> from the gateway.
                  Pick a cheap, fast one (e.g. <code>gpt-4o-mini</code>,{" "}
                  <code>gemini-2.5-flash</code>, <code>claude-haiku</code>) — it
                  only cleans grammar and structures the user prompt before search
                  and generation.
                </>
              ) : tab === "image_context" ? (
                <>
                  Showing <strong>OpenAI GPT models</strong> that support the{" "}
                  <code>image_generation</code> tool via the Responses API. These
                  models read your full post content and generate a contextually
                  relevant image. Add directly — you can also type a model slug
                  manually.
                </>
              ) : (
                <>
                  Showing models the gateway reports for the{" "}
                  <strong>{CATEGORY_META[tab].label}</strong> category. Add directly
                  — no need to check the Bifrost docs.
                </>
              )}
            </p>

            <div className="max-h-[50vh] space-y-1.5 overflow-y-auto pr-1">
              {catalogLoading && (
                <div className="flex h-24 items-center justify-center">
                  <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                </div>
              )}
              {!catalogLoading && catalogError && (
                <p className="py-6 text-center text-sm text-destructive">
                  {catalogError}
                </p>
              )}
              {!catalogLoading &&
                !catalogError &&
                (catalog || [])
                  .filter((c) => {
                    if (tab === "vision" || tab === "text_formatter") {
                      return c.category === "text";
                    }
                    if (tab === "image_context") {
                      return (
                        c.category === "text" &&
                        /^openai\/gpt-/i.test(c.id)
                      );
                    }
                    return c.category === tab;
                  })
                  .filter((c) =>
                    catalogSearch.trim()
                      ? c.id.toLowerCase().includes(catalogSearch.toLowerCase())
                      : true,
                  )
                  .map((c) => {
                    const already = existingModelStrings.has(
                      `${tab}:${c.id.toLowerCase()}`,
                    );
                    return (
                      <div
                        key={c.id}
                        className="flex items-center gap-2 rounded-md border border-border px-2.5 py-1.5"
                      >
                        <Badge
                          variant="secondary"
                          className={PROVIDER_STYLE[c.provider] || ""}
                        >
                          {c.provider}
                        </Badge>
                        <code className="min-w-0 flex-1 truncate font-mono text-[11px]">
                          {c.id}
                        </code>
                        <Button
                          type="button"
                          size="sm"
                          variant={already ? "ghost" : "outline"}
                          className="h-7"
                          disabled={already || adding}
                          onClick={() => handleAdd(tab, c.id, c.label)}
                        >
                          {already ? "Added" : "Add"}
                        </Button>
                      </div>
                    );
                  })}
              {!catalogLoading &&
                !catalogError &&
                (catalog || []).filter((c) => {
                  if (tab === "vision" || tab === "text_formatter") {
                    return c.category === "text";
                  }
                  if (tab === "image_context") {
                    return (
                      c.category === "text" &&
                      /^openai\/gpt-/i.test(c.id)
                    );
                  }
                  return c.category === tab;
                }).length === 0 && (
                  <p className="py-6 text-center text-sm text-muted-foreground">
                    No {CATEGORY_META[tab].label.toLowerCase()} models reported by
                    the gateway.
                  </p>
                )}
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
